// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module l3_generic_tanh_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_in,
        ap_return,
        grp_fu_722_p_din0,
        grp_fu_722_p_din1,
        grp_fu_722_p_dout0,
        grp_fu_722_p_ce
);

parameter    ap_ST_fsm_state1 = 141'd1;
parameter    ap_ST_fsm_state2 = 141'd2;
parameter    ap_ST_fsm_state3 = 141'd4;
parameter    ap_ST_fsm_state4 = 141'd8;
parameter    ap_ST_fsm_state5 = 141'd16;
parameter    ap_ST_fsm_state6 = 141'd32;
parameter    ap_ST_fsm_state7 = 141'd64;
parameter    ap_ST_fsm_state8 = 141'd128;
parameter    ap_ST_fsm_state9 = 141'd256;
parameter    ap_ST_fsm_state10 = 141'd512;
parameter    ap_ST_fsm_state11 = 141'd1024;
parameter    ap_ST_fsm_state12 = 141'd2048;
parameter    ap_ST_fsm_state13 = 141'd4096;
parameter    ap_ST_fsm_state14 = 141'd8192;
parameter    ap_ST_fsm_state15 = 141'd16384;
parameter    ap_ST_fsm_state16 = 141'd32768;
parameter    ap_ST_fsm_state17 = 141'd65536;
parameter    ap_ST_fsm_state18 = 141'd131072;
parameter    ap_ST_fsm_state19 = 141'd262144;
parameter    ap_ST_fsm_state20 = 141'd524288;
parameter    ap_ST_fsm_state21 = 141'd1048576;
parameter    ap_ST_fsm_state22 = 141'd2097152;
parameter    ap_ST_fsm_state23 = 141'd4194304;
parameter    ap_ST_fsm_state24 = 141'd8388608;
parameter    ap_ST_fsm_state25 = 141'd16777216;
parameter    ap_ST_fsm_state26 = 141'd33554432;
parameter    ap_ST_fsm_state27 = 141'd67108864;
parameter    ap_ST_fsm_state28 = 141'd134217728;
parameter    ap_ST_fsm_state29 = 141'd268435456;
parameter    ap_ST_fsm_state30 = 141'd536870912;
parameter    ap_ST_fsm_state31 = 141'd1073741824;
parameter    ap_ST_fsm_state32 = 141'd2147483648;
parameter    ap_ST_fsm_state33 = 141'd4294967296;
parameter    ap_ST_fsm_state34 = 141'd8589934592;
parameter    ap_ST_fsm_state35 = 141'd17179869184;
parameter    ap_ST_fsm_state36 = 141'd34359738368;
parameter    ap_ST_fsm_state37 = 141'd68719476736;
parameter    ap_ST_fsm_state38 = 141'd137438953472;
parameter    ap_ST_fsm_state39 = 141'd274877906944;
parameter    ap_ST_fsm_state40 = 141'd549755813888;
parameter    ap_ST_fsm_state41 = 141'd1099511627776;
parameter    ap_ST_fsm_state42 = 141'd2199023255552;
parameter    ap_ST_fsm_state43 = 141'd4398046511104;
parameter    ap_ST_fsm_state44 = 141'd8796093022208;
parameter    ap_ST_fsm_state45 = 141'd17592186044416;
parameter    ap_ST_fsm_state46 = 141'd35184372088832;
parameter    ap_ST_fsm_state47 = 141'd70368744177664;
parameter    ap_ST_fsm_state48 = 141'd140737488355328;
parameter    ap_ST_fsm_state49 = 141'd281474976710656;
parameter    ap_ST_fsm_state50 = 141'd562949953421312;
parameter    ap_ST_fsm_state51 = 141'd1125899906842624;
parameter    ap_ST_fsm_state52 = 141'd2251799813685248;
parameter    ap_ST_fsm_state53 = 141'd4503599627370496;
parameter    ap_ST_fsm_state54 = 141'd9007199254740992;
parameter    ap_ST_fsm_state55 = 141'd18014398509481984;
parameter    ap_ST_fsm_state56 = 141'd36028797018963968;
parameter    ap_ST_fsm_state57 = 141'd72057594037927936;
parameter    ap_ST_fsm_state58 = 141'd144115188075855872;
parameter    ap_ST_fsm_state59 = 141'd288230376151711744;
parameter    ap_ST_fsm_state60 = 141'd576460752303423488;
parameter    ap_ST_fsm_state61 = 141'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 141'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 141'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 141'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 141'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 141'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 141'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 141'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 141'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 141'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 141'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 141'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 141'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 141'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 141'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 141'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 141'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 141'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 141'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 141'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 141'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 141'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 141'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 141'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 141'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 141'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 141'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 141'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 141'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 141'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 141'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 141'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 141'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 141'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 141'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 141'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 141'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 141'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 141'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 141'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 141'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 141'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 141'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 141'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 141'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 141'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 141'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 141'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 141'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 141'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 141'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 141'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 141'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 141'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 141'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 141'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 141'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 141'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 141'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 141'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 141'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 141'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 141'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 141'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 141'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 141'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 141'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 141'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 141'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 141'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 141'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 141'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 141'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 141'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state135 = 141'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state136 = 141'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state137 = 141'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state138 = 141'd174224571863520493293247799005065324265472;
parameter    ap_ST_fsm_state139 = 141'd348449143727040986586495598010130648530944;
parameter    ap_ST_fsm_state140 = 141'd696898287454081973172991196020261297061888;
parameter    ap_ST_fsm_state141 = 141'd1393796574908163946345982392040522594123776;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] t_in;
output  [63:0] ap_return;
output  [63:0] grp_fu_722_p_din0;
output  [63:0] grp_fu_722_p_din1;
input  [63:0] grp_fu_722_p_dout0;
output   grp_fu_722_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [140:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_fu_98_p2;
reg   [63:0] reg_127;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state82;
reg   [0:0] p_Result_s_reg_324;
wire   [10:0] tmp_7_fu_146_p4;
reg   [10:0] tmp_7_reg_329;
wire   [62:0] p_Result_1_fu_160_p1;
reg   [62:0] p_Result_1_reg_334;
wire   [63:0] abst_in_fu_168_p1;
reg   [63:0] abst_in_reg_339;
wire   [0:0] icmp_ln824_fu_174_p2;
reg   [0:0] icmp_ln824_reg_347;
wire   [0:0] icmp_ln840_fu_180_p2;
reg   [0:0] icmp_ln840_reg_351;
wire   [0:0] and_ln75_fu_198_p2;
reg   [0:0] and_ln75_reg_355;
wire   [0:0] icmp_ln828_fu_204_p2;
reg   [0:0] icmp_ln828_reg_359;
wire   [0:0] grp_fu_117_p2;
reg   [0:0] tmp_5_reg_364;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln840_1_fu_210_p2;
reg   [0:0] icmp_ln840_1_reg_368;
wire   [63:0] bitcast_ln84_fu_222_p1;
wire    ap_CS_fsm_state3;
wire   [63:0] x_3_fu_227_p3;
reg   [63:0] x_3_reg_378;
wire    ap_CS_fsm_state7;
wire   [63:0] grp_exp_generic_double_s_fu_87_ap_return;
reg   [63:0] tmp_reg_394;
wire    ap_CS_fsm_state19;
wire   [63:0] grp_fu_112_p2;
reg   [63:0] div_reg_399;
wire    ap_CS_fsm_state51;
wire   [63:0] bitcast_ln95_1_fu_312_p1;
wire    ap_CS_fsm_state57;
wire    ap_CS_fsm_state78;
wire   [63:0] grp_fu_108_p2;
reg   [63:0] resultf_reg_414;
wire    ap_CS_fsm_state86;
wire   [63:0] select_ln67_fu_317_p3;
wire    ap_CS_fsm_state141;
wire    grp_exp_generic_double_s_fu_87_ap_start;
wire    grp_exp_generic_double_s_fu_87_ap_done;
wire    grp_exp_generic_double_s_fu_87_ap_idle;
wire    grp_exp_generic_double_s_fu_87_ap_ready;
reg   [63:0] expx_reg_58;
wire   [0:0] p_Result_2_fu_238_p3;
wire   [0:0] xor_ln9_fu_275_p2;
wire   [0:0] xor_ln10_fu_263_p2;
reg   [63:0] ap_phi_mux_resultf_3_phi_fu_74_p10;
reg   [63:0] resultf_3_reg_70;
wire    ap_CS_fsm_state87;
wire    ap_CS_fsm_state56;
reg    grp_exp_generic_double_s_fu_87_ap_start_reg;
reg   [140:0] ap_NS_fsm;
wire    ap_NS_fsm_state8;
wire    ap_CS_fsm_state8;
reg   [63:0] grp_fu_98_p0;
reg   [63:0] grp_fu_98_p1;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state52;
wire   [63:0] grp_fu_108_p0;
wire   [63:0] grp_fu_108_p1;
wire    ap_CS_fsm_state83;
reg   [63:0] grp_fu_112_p0;
wire    ap_CS_fsm_state30;
wire   [63:0] grp_fu_117_p0;
wire   [10:0] tmp_9_fu_246_p4;
wire   [63:0] data_V_fu_134_p1;
wire   [63:0] zext_ln368_fu_164_p1;
wire   [51:0] tmp_8_fu_156_p1;
wire   [0:0] icmp_ln824_1_fu_186_p2;
wire   [0:0] icmp_ln824_2_fu_192_p2;
wire   [63:0] or_ln_fu_215_p3;
wire   [63:0] data_V_1_fu_234_p1;
wire   [0:0] grp_fu_122_p2;
wire   [0:0] icmp_ln844_fu_257_p2;
wire   [0:0] icmp_ln832_fu_269_p2;
wire   [63:0] bitcast_ln112_fu_281_p1;
wire   [63:0] xor_ln112_fu_285_p2;
wire   [63:0] bitcast_ln112_1_fu_291_p1;
wire   [63:0] bitcast_ln95_fu_302_p1;
wire   [63:0] xor_ln95_fu_306_p2;
reg   [1:0] grp_fu_98_opcode;
wire    grp_fu_108_ce;
wire   [63:0] select_ln108_fu_295_p3;
reg   [63:0] ap_return_preg;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 141'd1;
#0 grp_exp_generic_double_s_fu_87_ap_start_reg = 1'b0;
#0 ap_return_preg = 64'd0;
end

l3_exp_generic_double_s grp_exp_generic_double_s_fu_87(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_exp_generic_double_s_fu_87_ap_start),
    .ap_done(grp_exp_generic_double_s_fu_87_ap_done),
    .ap_idle(grp_exp_generic_double_s_fu_87_ap_idle),
    .ap_ready(grp_exp_generic_double_s_fu_87_ap_ready),
    .x(x_3_reg_378),
    .ap_return(grp_exp_generic_double_s_fu_87_ap_return)
);

l3_dadddsub_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadddsub_64ns_64ns_64_5_full_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_98_p0),
    .din1(grp_fu_98_p1),
    .opcode(grp_fu_98_opcode),
    .ce(1'b1),
    .dout(grp_fu_98_p2)
);

l3_ddiv_64ns_64ns_64_22_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 22 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_22_no_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_112_p0),
    .din1(reg_127),
    .ce(1'b1),
    .dout(grp_fu_112_p2)
);

l3_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_117_p0),
    .din1(64'd4626885667169763328),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_117_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state56)) begin
            ap_return_preg <= select_ln108_fu_295_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_exp_generic_double_s_fu_87_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state8) & (1'b1 == ap_CS_fsm_state7))) begin
            grp_exp_generic_double_s_fu_87_ap_start_reg <= 1'b1;
        end else if ((grp_exp_generic_double_s_fu_87_ap_ready == 1'b1)) begin
            grp_exp_generic_double_s_fu_87_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((xor_ln10_fu_263_p2 == 1'd1) & (p_Result_2_fu_238_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((xor_ln9_fu_275_p2 == 1'd1) & (p_Result_2_fu_238_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state7)))) begin
        expx_reg_58 <= x_3_fu_227_p3;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        expx_reg_58 <= grp_fu_98_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_117_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        resultf_3_reg_70 <= 64'd4607182418800017408;
    end else if ((1'b1 == ap_CS_fsm_state141)) begin
        resultf_3_reg_70 <= select_ln67_fu_317_p3;
    end else if (((icmp_ln840_1_reg_368 == 1'd0) & (tmp_5_reg_364 == 1'd1) & (1'b1 == ap_CS_fsm_state56) & (1'd0 == and_ln75_reg_355) & (icmp_ln840_reg_351 == 1'd0) & (icmp_ln824_reg_347 == 1'd0))) begin
        resultf_3_reg_70 <= grp_fu_98_p2;
    end else if ((1'b1 == ap_CS_fsm_state78)) begin
        resultf_3_reg_70 <= grp_fu_112_p2;
    end else if ((1'b1 == ap_CS_fsm_state87)) begin
        resultf_3_reg_70 <= resultf_reg_414;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        abst_in_reg_339[62 : 0] <= abst_in_fu_168_p1[62 : 0];
        icmp_ln824_reg_347 <= icmp_ln824_fu_174_p2;
        p_Result_1_reg_334 <= p_Result_1_fu_160_p1;
        p_Result_s_reg_324 <= data_V_fu_134_p1[32'd63];
        tmp_7_reg_329 <= {{data_V_fu_134_p1[62:52]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln840_fu_180_p2 == 1'd0) & (icmp_ln824_fu_174_p2 == 1'd0))) begin
        and_ln75_reg_355 <= and_ln75_fu_198_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        div_reg_399 <= grp_fu_112_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln824_fu_174_p2 == 1'd1))) begin
        icmp_ln828_reg_359 <= icmp_ln828_fu_204_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_117_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln840_1_reg_368 <= icmp_ln840_1_fu_210_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln824_fu_174_p2 == 1'd0))) begin
        icmp_ln840_reg_351 <= icmp_ln840_fu_180_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state24))) begin
        reg_127 <= grp_fu_98_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state86)) begin
        resultf_reg_414 <= grp_fu_722_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_5_reg_364 <= grp_fu_117_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tmp_reg_394 <= grp_exp_generic_double_s_fu_87_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        x_3_reg_378 <= x_3_fu_227_p3;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state56) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln840_1_reg_368 == 1'd0) & (tmp_5_reg_364 == 1'd1) & (1'b1 == ap_CS_fsm_state56) & (1'd0 == and_ln75_reg_355) & (icmp_ln840_reg_351 == 1'd0) & (icmp_ln824_reg_347 == 1'd0))) begin
        ap_phi_mux_resultf_3_phi_fu_74_p10 = grp_fu_98_p2;
    end else begin
        ap_phi_mux_resultf_3_phi_fu_74_p10 = resultf_3_reg_70;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        ap_return = select_ln108_fu_295_p3;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        grp_fu_112_p0 = bitcast_ln95_1_fu_312_p1;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_112_p0 = 64'd4611686018427387904;
    end else begin
        grp_fu_112_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | ((icmp_ln840_1_reg_368 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_fu_98_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state20) | ((icmp_ln840_1_reg_368 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (((icmp_ln840_fu_180_p2 == 1'd1) & (icmp_ln824_fu_174_p2 == 1'd0)) | ((1'd1 == and_ln75_fu_198_p2) & (icmp_ln824_fu_174_p2 == 1'd0)))))) begin
        grp_fu_98_opcode = 2'd0;
    end else begin
        grp_fu_98_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        grp_fu_98_p0 = 64'd4607182418800017408;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_98_p0 = expx_reg_58;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_98_p0 = tmp_reg_394;
    end else if (((icmp_ln840_1_reg_368 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_98_p0 = abst_in_reg_339;
    end else if (((icmp_ln840_1_reg_368 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_98_p0 = bitcast_ln84_fu_222_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_98_p0 = abst_in_fu_168_p1;
    end else begin
        grp_fu_98_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        grp_fu_98_p1 = div_reg_399;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_98_p1 = 64'd4611686018427387904;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_98_p1 = 64'd13830554455654793216;
    end else if ((((icmp_ln840_1_reg_368 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln840_1_reg_368 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_fu_98_p1 = abst_in_reg_339;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_98_p1 = 64'd4607182418800017408;
    end else begin
        grp_fu_98_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'd0 == and_ln75_fu_198_p2) & (icmp_ln840_fu_180_p2 == 1'd0) & (icmp_ln824_fu_174_p2 == 1'd0) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (((icmp_ln840_fu_180_p2 == 1'd1) & (icmp_ln824_fu_174_p2 == 1'd0)) | ((1'd1 == and_ln75_fu_198_p2) & (icmp_ln824_fu_174_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state79;
            end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln824_fu_174_p2 == 1'd1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state88;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fu_117_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (((xor_ln10_fu_263_p2 == 1'd1) & (p_Result_2_fu_238_p3 == 1'd0)) | ((xor_ln9_fu_275_p2 == 1'd1) & (p_Result_2_fu_238_p3 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((icmp_ln840_1_reg_368 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state135;
        end
        ap_ST_fsm_state135 : begin
            ap_NS_fsm = ap_ST_fsm_state136;
        end
        ap_ST_fsm_state136 : begin
            ap_NS_fsm = ap_ST_fsm_state137;
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            ap_NS_fsm = ap_ST_fsm_state139;
        end
        ap_ST_fsm_state139 : begin
            ap_NS_fsm = ap_ST_fsm_state140;
        end
        ap_ST_fsm_state140 : begin
            ap_NS_fsm = ap_ST_fsm_state141;
        end
        ap_ST_fsm_state141 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abst_in_fu_168_p1 = zext_ln368_fu_164_p1;

assign and_ln75_fu_198_p2 = (icmp_ln824_2_fu_192_p2 & icmp_ln824_1_fu_186_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state141 = ap_CS_fsm[32'd140];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state82 = ap_CS_fsm[32'd81];

assign ap_CS_fsm_state83 = ap_CS_fsm[32'd82];

assign ap_CS_fsm_state86 = ap_CS_fsm[32'd85];

assign ap_CS_fsm_state87 = ap_CS_fsm[32'd86];

assign ap_NS_fsm_state8 = ap_NS_fsm[32'd7];

assign bitcast_ln112_1_fu_291_p1 = xor_ln112_fu_285_p2;

assign bitcast_ln112_fu_281_p1 = ap_phi_mux_resultf_3_phi_fu_74_p10;

assign bitcast_ln84_fu_222_p1 = or_ln_fu_215_p3;

assign bitcast_ln95_1_fu_312_p1 = xor_ln95_fu_306_p2;

assign bitcast_ln95_fu_302_p1 = expx_reg_58;

assign data_V_1_fu_234_p1 = x_3_fu_227_p3;

assign data_V_fu_134_p1 = t_in;

assign grp_exp_generic_double_s_fu_87_ap_start = grp_exp_generic_double_s_fu_87_ap_start_reg;

assign grp_fu_108_ce = 1'b1;

assign grp_fu_108_p0 = abst_in_reg_339;

assign grp_fu_108_p1 = reg_127;

assign grp_fu_108_p2 = grp_fu_722_p_dout0;

assign grp_fu_117_p0 = zext_ln368_fu_164_p1;

assign grp_fu_122_p2 = ((tmp_9_fu_246_p4 == 11'd0) ? 1'b1 : 1'b0);

assign grp_fu_722_p_ce = 1'b1;

assign grp_fu_722_p_din0 = abst_in_reg_339;

assign grp_fu_722_p_din1 = reg_127;

assign icmp_ln824_1_fu_186_p2 = ((tmp_7_fu_146_p4 == 11'd968) ? 1'b1 : 1'b0);

assign icmp_ln824_2_fu_192_p2 = ((tmp_8_fu_156_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln824_fu_174_p2 = ((tmp_7_fu_146_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln828_fu_204_p2 = ((tmp_8_fu_156_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln832_fu_269_p2 = ((tmp_9_fu_246_p4 < 11'd996) ? 1'b1 : 1'b0);

assign icmp_ln840_1_fu_210_p2 = ((tmp_7_reg_329 < 11'd1023) ? 1'b1 : 1'b0);

assign icmp_ln840_fu_180_p2 = ((tmp_7_fu_146_p4 < 11'd968) ? 1'b1 : 1'b0);

assign icmp_ln844_fu_257_p2 = ((tmp_9_fu_246_p4 < 11'd997) ? 1'b1 : 1'b0);

assign or_ln_fu_215_p3 = {{1'd1}, {p_Result_1_reg_334}};

assign p_Result_1_fu_160_p1 = data_V_fu_134_p1[62:0];

assign p_Result_2_fu_238_p3 = data_V_1_fu_234_p1[32'd63];

assign select_ln108_fu_295_p3 = ((p_Result_s_reg_324[0:0] == 1'b1) ? bitcast_ln112_1_fu_291_p1 : ap_phi_mux_resultf_3_phi_fu_74_p10);

assign select_ln67_fu_317_p3 = ((icmp_ln828_reg_359[0:0] == 1'b1) ? 64'd9223372036854775807 : 64'd4607182418800017408);

assign tmp_7_fu_146_p4 = {{data_V_fu_134_p1[62:52]}};

assign tmp_8_fu_156_p1 = data_V_fu_134_p1[51:0];

assign tmp_9_fu_246_p4 = {{data_V_1_fu_234_p1[62:52]}};

assign x_3_fu_227_p3 = ((icmp_ln840_1_reg_368[0:0] == 1'b1) ? grp_fu_98_p2 : grp_fu_98_p2);

assign xor_ln10_fu_263_p2 = (icmp_ln844_fu_257_p2 ^ grp_fu_122_p2);

assign xor_ln112_fu_285_p2 = (bitcast_ln112_fu_281_p1 ^ 64'd9223372036854775808);

assign xor_ln95_fu_306_p2 = (bitcast_ln95_fu_302_p1 ^ 64'd9223372036854775808);

assign xor_ln9_fu_275_p2 = (icmp_ln832_fu_269_p2 ^ grp_fu_122_p2);

assign zext_ln368_fu_164_p1 = p_Result_1_fu_160_p1;

always @ (posedge ap_clk) begin
    abst_in_reg_339[63] <= 1'b0;
end

endmodule //l3_generic_tanh_double_s
