// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module l3_exp_generic_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] x;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [57:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1;
wire   [7:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [41:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [0:0] p_Result_9_fu_265_p3;
reg   [0:0] p_Result_9_reg_1160;
reg   [0:0] p_Result_9_reg_1160_pp0_iter1_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter2_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter3_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter4_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter5_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter6_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter7_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter8_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter9_reg;
reg   [0:0] p_Result_9_reg_1160_pp0_iter10_reg;
wire   [0:0] x_is_NaN_fu_299_p2;
reg   [0:0] x_is_NaN_reg_1165;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter1_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter2_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter3_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter4_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter5_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter6_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter7_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter8_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter9_reg;
reg   [0:0] x_is_NaN_reg_1165_pp0_iter10_reg;
wire   [0:0] x_is_inf_fu_311_p2;
reg   [0:0] x_is_inf_reg_1173;
reg   [0:0] x_is_inf_reg_1173_pp0_iter1_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter2_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter3_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter4_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter5_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter6_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter7_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter8_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter9_reg;
reg   [0:0] x_is_inf_reg_1173_pp0_iter10_reg;
wire   [53:0] select_ln253_fu_341_p3;
reg   [53:0] select_ln253_reg_1180;
reg   [53:0] select_ln253_reg_1180_pp0_iter1_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter2_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter3_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter4_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter5_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter6_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter7_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter8_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter9_reg;
reg   [53:0] select_ln253_reg_1180_pp0_iter10_reg;
reg   [0:0] p_Result_11_reg_1185;
reg   [0:0] p_Result_11_reg_1185_pp0_iter1_reg;
wire   [58:0] trunc_ln657_fu_463_p1;
reg   [58:0] trunc_ln657_reg_1195;
reg   [58:0] trunc_ln657_reg_1195_pp0_iter1_reg;
reg   [58:0] trunc_ln657_reg_1195_pp0_iter2_reg;
reg   [58:0] trunc_ln657_reg_1195_pp0_iter3_reg;
reg   [58:0] trunc_ln657_reg_1195_pp0_iter4_reg;
wire   [0:0] icmp_ln338_fu_467_p2;
reg   [0:0] icmp_ln338_reg_1200;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter1_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter2_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter3_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter4_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter5_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter6_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter7_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter8_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter9_reg;
reg   [0:0] icmp_ln338_reg_1200_pp0_iter10_reg;
wire   [0:0] icmp_ln1453_fu_489_p2;
reg   [0:0] icmp_ln1453_reg_1208;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter1_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter2_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter3_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter4_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter5_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter6_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter7_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter8_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter9_reg;
reg   [0:0] icmp_ln1453_reg_1208_pp0_iter10_reg;
wire  signed [12:0] ret_V_8_fu_545_p3;
reg  signed [12:0] ret_V_8_reg_1218;
reg  signed [12:0] ret_V_8_reg_1218_pp0_iter4_reg;
reg  signed [12:0] ret_V_8_reg_1218_pp0_iter5_reg;
reg  signed [12:0] ret_V_8_reg_1218_pp0_iter6_reg;
reg  signed [12:0] ret_V_8_reg_1218_pp0_iter7_reg;
reg  signed [12:0] ret_V_8_reg_1218_pp0_iter8_reg;
reg  signed [12:0] ret_V_8_reg_1218_pp0_iter9_reg;
reg  signed [12:0] ret_V_8_reg_1218_pp0_iter10_reg;
reg   [57:0] tmp_2_reg_1225;
reg   [7:0] m_diff_hi_V_reg_1230;
reg   [7:0] m_diff_hi_V_reg_1230_pp0_iter6_reg;
reg   [7:0] m_diff_hi_V_reg_1230_pp0_iter7_reg;
reg   [7:0] m_diff_hi_V_reg_1230_pp0_iter8_reg;
reg   [7:0] Z2_V_reg_1235;
reg   [7:0] Z2_V_reg_1235_pp0_iter6_reg;
reg   [7:0] Z2_V_reg_1235_pp0_iter7_reg;
reg   [7:0] Z2_V_reg_1235_pp0_iter8_reg;
wire   [7:0] Z3_V_fu_604_p4;
reg   [7:0] Z3_V_reg_1242;
reg   [7:0] Z3_V_reg_1242_pp0_iter6_reg;
wire   [34:0] Z4_fu_614_p1;
reg   [34:0] Z4_reg_1247;
wire   [35:0] ret_V_9_fu_655_p2;
reg   [35:0] ret_V_9_reg_1262;
reg   [25:0] f_Z3_reg_1268;
wire   [42:0] ret_V_10_fu_661_p4;
reg   [42:0] ret_V_10_reg_1273;
wire   [35:0] add_ln657_fu_696_p2;
reg   [35:0] add_ln657_reg_1278;
wire   [43:0] exp_Z2P_m_1_V_fu_711_p2;
reg   [43:0] exp_Z2P_m_1_V_reg_1288;
wire   [39:0] tmp_3_fu_717_p4;
reg   [39:0] tmp_3_reg_1293;
reg   [35:0] trunc_ln657_5_reg_1298;
reg   [49:0] exp_Z1P_m_1_V_reg_1308;
wire   [57:0] ret_V_11_fu_816_p2;
reg   [57:0] ret_V_11_reg_1313;
wire   [99:0] r_V_15_fu_829_p2;
reg   [99:0] r_V_15_reg_1318;
wire   [56:0] trunc_ln1146_fu_835_p1;
reg   [56:0] trunc_ln1146_reg_1325;
wire   [55:0] trunc_ln1146_2_fu_839_p1;
reg   [55:0] trunc_ln1146_2_reg_1330;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln488_1_fu_628_p1;
wire   [63:0] zext_ln488_2_fu_633_p1;
wire   [63:0] zext_ln488_3_fu_701_p1;
wire   [63:0] zext_ln488_fu_760_p1;
wire   [63:0] data_V_fu_261_p1;
wire   [10:0] tmp_20_fu_273_p4;
wire   [51:0] tmp_21_fu_283_p1;
wire   [0:0] icmp_ln209_fu_287_p2;
wire   [0:0] icmp_ln18_fu_293_p2;
wire   [0:0] icmp_ln824_fu_305_p2;
wire   [11:0] zext_ln510_fu_317_p1;
wire   [53:0] p_Result_10_fu_327_p3;
wire   [53:0] e_frac_V_1_fu_335_p2;
wire   [60:0] m_frac_l_V_fu_349_p3;
wire   [11:0] m_exp_fu_321_p2;
wire   [10:0] sub_ln1311_fu_369_p2;
wire   [0:0] isNeg_fu_361_p3;
wire  signed [11:0] sext_ln1311_fu_375_p1;
wire   [11:0] ush_fu_379_p3;
wire  signed [31:0] sh_prom_i_i360_cast_cast_cast_fu_387_p1;
wire  signed [70:0] sext_ln256_fu_357_p1;
wire   [70:0] sh_prom_i_i360_cast_cast_cast_cast_fu_391_p1;
wire   [70:0] r_V_fu_395_p2;
wire   [70:0] r_V_1_fu_401_p2;
wire   [70:0] r_V_13_fu_407_p3;
wire   [63:0] m_fix_l_fu_415_p4;
wire   [63:0] sh_prom_i_i340_cast_cast_cast_cast_fu_425_p1;
wire  signed [15:0] m_fix_hi_fu_441_p4;
wire   [63:0] r_V_3_fu_429_p2;
wire   [63:0] r_V_4_fu_435_p2;
wire   [63:0] select_ln1322_fu_473_p3;
wire   [70:0] shl_ln_fu_481_p3;
wire  signed [18:0] rhs_fu_495_p3;
wire  signed [30:0] grp_fu_1149_p3;
wire   [17:0] trunc_ln805_fu_522_p1;
wire   [12:0] ret_V_cast_fu_506_p4;
wire   [0:0] icmp_ln805_fu_525_p2;
wire   [12:0] ret_V_fu_531_p2;
wire   [0:0] p_Result_s_fu_515_p3;
wire   [12:0] select_ln804_fu_537_p3;
wire   [70:0] r_V_8_fu_556_p2;
wire   [58:0] and_ln_fu_572_p3;
wire   [58:0] m_diff_V_fu_579_p2;
wire   [7:0] Z4_ind_fu_618_p4;
wire   [9:0] r_fu_638_p4;
wire   [35:0] zext_ln657_fu_648_p1;
wire   [35:0] zext_ln657_1_fu_651_p1;
wire   [42:0] r_V_10_fu_676_p0;
wire   [35:0] r_V_10_fu_676_p1;
wire   [78:0] r_V_10_fu_676_p2;
wire   [19:0] trunc_ln657_4_fu_682_p4;
wire   [35:0] zext_ln657_2_fu_692_p1;
wire   [43:0] zext_ln657_3_fu_708_p1;
wire   [43:0] zext_ln1146_fu_705_p1;
wire   [48:0] exp_Z2_m_1_V_fu_727_p4;
wire   [48:0] r_V_11_fu_744_p0;
wire   [43:0] r_V_11_fu_744_p1;
wire   [92:0] r_V_11_fu_744_p2;
wire   [50:0] lhs_V_fu_764_p5;
wire   [43:0] zext_ln657_4_fu_778_p1;
wire   [43:0] add_ln657_2_fu_781_p2;
wire   [51:0] zext_ln657_5_fu_786_p1;
wire   [51:0] zext_ln1146_1_fu_774_p1;
wire   [51:0] exp_Z1P_m_1_l_V_fu_790_p2;
wire   [49:0] exp_Z1_hi_V_fu_806_p4;
wire   [49:0] r_V_15_fu_829_p0;
wire   [49:0] r_V_15_fu_829_p1;
wire   [0:0] xor_ln964_fu_843_p2;
wire   [0:0] x_is_pinf_fu_848_p2;
wire   [0:0] or_ln214_fu_853_p2;
wire   [106:0] lhs_V_3_fu_866_p3;
wire   [106:0] zext_ln1146_2_fu_873_p1;
wire   [104:0] trunc_ln1146_1_fu_889_p3;
wire   [104:0] zext_ln1146_4_fu_886_p1;
wire   [105:0] trunc_ln2_fu_879_p3;
wire   [105:0] zext_ln1146_3_fu_876_p1;
wire   [106:0] ret_V_6_fu_896_p2;
wire   [0:0] tmp_16_fu_914_p3;
wire   [12:0] r_exp_V_fu_922_p2;
wire   [12:0] r_exp_V_2_fu_927_p3;
wire   [2:0] tmp_17_fu_934_p4;
wire   [0:0] icmp_ln840_fu_944_p2;
wire   [0:0] tmp_18_fu_955_p3;
wire   [105:0] add_ln1146_2_fu_908_p2;
wire   [104:0] add_ln1146_1_fu_902_p2;
wire   [51:0] tmp_fu_976_p4;
wire   [51:0] tmp_s_fu_986_p4;
wire   [10:0] trunc_ln167_fu_1004_p1;
wire   [10:0] out_exp_V_fu_1008_p2;
wire   [51:0] tmp_22_fu_996_p3;
wire   [62:0] p_Result_12_fu_1014_p3;
wire   [63:0] zext_ln368_fu_1022_p1;
wire   [0:0] or_ln18_fu_1030_p2;
wire   [0:0] or_ln338_fu_950_p2;
wire   [0:0] xor_ln338_fu_1045_p2;
wire   [0:0] and_ln338_fu_1040_p2;
wire   [0:0] and_ln840_fu_1050_p2;
wire   [0:0] or_ln840_fu_1056_p2;
wire   [0:0] xor_ln18_fu_1034_p2;
wire   [0:0] sel_tmp7_fu_1062_p2;
wire   [63:0] select_ln344_fu_962_p3;
wire   [63:0] bitcast_ln521_fu_1026_p1;
wire   [63:0] sel_tmp8_fu_1068_p3;
wire   [0:0] xor_ln18_1_fu_1083_p2;
wire   [0:0] and_ln18_fu_1088_p2;
wire   [63:0] select_ln214_fu_858_p3;
wire   [63:0] select_ln18_fu_1076_p3;
wire   [0:0] xor_ln338_1_fu_1101_p2;
wire   [0:0] or_ln840_1_fu_1112_p2;
wire   [0:0] and_ln338_1_fu_1107_p2;
wire   [0:0] xor_ln840_fu_1117_p2;
wire   [0:0] or_ln840_2_fu_1123_p2;
wire   [0:0] tmp27_fu_1129_p2;
wire   [0:0] icmp_ln844_fu_970_p2;
wire   [0:0] sel_tmp23_fu_1135_p2;
wire   [63:0] select_ln18_1_fu_1093_p3;
wire   [15:0] grp_fu_1149_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to10;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [78:0] r_V_10_fu_676_p00;
wire   [78:0] r_V_10_fu_676_p10;
wire   [92:0] r_V_11_fu_744_p00;
wire   [92:0] r_V_11_fu_744_p10;
wire   [99:0] r_V_15_fu_829_p00;
wire   [99:0] r_V_15_fu_829_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
end

l3_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb #(
    .DataWidth( 58 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0)
);

l3_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud #(
    .DataWidth( 26 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0),
    .address1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1),
    .ce1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1),
    .q1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1)
);

l3_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe #(
    .DataWidth( 42 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0)
);

l3_mul_13s_71s_71_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 71 ),
    .dout_WIDTH( 71 ))
mul_13s_71s_71_1_1_U1(
    .din0(ret_V_8_reg_1218),
    .din1(71'd1636647506585939924452),
    .dout(r_V_8_fu_556_p2)
);

l3_mul_43ns_36ns_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 43 ),
    .din1_WIDTH( 36 ),
    .dout_WIDTH( 79 ))
mul_43ns_36ns_79_1_1_U2(
    .din0(r_V_10_fu_676_p0),
    .din1(r_V_10_fu_676_p1),
    .dout(r_V_10_fu_676_p2)
);

l3_mul_49ns_44ns_93_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 93 ))
mul_49ns_44ns_93_1_1_U3(
    .din0(r_V_11_fu_744_p0),
    .din1(r_V_11_fu_744_p1),
    .dout(r_V_11_fu_744_p2)
);

l3_mul_50ns_50ns_100_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 100 ))
mul_50ns_50ns_100_1_1_U4(
    .din0(r_V_15_fu_829_p0),
    .din1(r_V_15_fu_829_p1),
    .dout(r_V_15_fu_829_p2)
);

l3_mac_muladd_16s_16ns_19s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16ns_19s_31_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m_fix_hi_fu_441_p4),
    .din1(grp_fu_1149_p1),
    .din2(rhs_fu_495_p3),
    .ce(1'b1),
    .dout(grp_fu_1149_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Z2_V_reg_1235 <= {{m_diff_V_fu_579_p2[50:43]}};
        Z2_V_reg_1235_pp0_iter6_reg <= Z2_V_reg_1235;
        Z2_V_reg_1235_pp0_iter7_reg <= Z2_V_reg_1235_pp0_iter6_reg;
        Z2_V_reg_1235_pp0_iter8_reg <= Z2_V_reg_1235_pp0_iter7_reg;
        Z3_V_reg_1242 <= {{m_diff_V_fu_579_p2[42:35]}};
        Z3_V_reg_1242_pp0_iter6_reg <= Z3_V_reg_1242;
        Z4_reg_1247 <= Z4_fu_614_p1;
        add_ln657_reg_1278 <= add_ln657_fu_696_p2;
        exp_Z1P_m_1_V_reg_1308 <= {{exp_Z1P_m_1_l_V_fu_790_p2[51:2]}};
        exp_Z2P_m_1_V_reg_1288 <= exp_Z2P_m_1_V_fu_711_p2;
        icmp_ln1453_reg_1208_pp0_iter10_reg <= icmp_ln1453_reg_1208_pp0_iter9_reg;
        icmp_ln1453_reg_1208_pp0_iter2_reg <= icmp_ln1453_reg_1208_pp0_iter1_reg;
        icmp_ln1453_reg_1208_pp0_iter3_reg <= icmp_ln1453_reg_1208_pp0_iter2_reg;
        icmp_ln1453_reg_1208_pp0_iter4_reg <= icmp_ln1453_reg_1208_pp0_iter3_reg;
        icmp_ln1453_reg_1208_pp0_iter5_reg <= icmp_ln1453_reg_1208_pp0_iter4_reg;
        icmp_ln1453_reg_1208_pp0_iter6_reg <= icmp_ln1453_reg_1208_pp0_iter5_reg;
        icmp_ln1453_reg_1208_pp0_iter7_reg <= icmp_ln1453_reg_1208_pp0_iter6_reg;
        icmp_ln1453_reg_1208_pp0_iter8_reg <= icmp_ln1453_reg_1208_pp0_iter7_reg;
        icmp_ln1453_reg_1208_pp0_iter9_reg <= icmp_ln1453_reg_1208_pp0_iter8_reg;
        icmp_ln338_reg_1200_pp0_iter10_reg <= icmp_ln338_reg_1200_pp0_iter9_reg;
        icmp_ln338_reg_1200_pp0_iter2_reg <= icmp_ln338_reg_1200_pp0_iter1_reg;
        icmp_ln338_reg_1200_pp0_iter3_reg <= icmp_ln338_reg_1200_pp0_iter2_reg;
        icmp_ln338_reg_1200_pp0_iter4_reg <= icmp_ln338_reg_1200_pp0_iter3_reg;
        icmp_ln338_reg_1200_pp0_iter5_reg <= icmp_ln338_reg_1200_pp0_iter4_reg;
        icmp_ln338_reg_1200_pp0_iter6_reg <= icmp_ln338_reg_1200_pp0_iter5_reg;
        icmp_ln338_reg_1200_pp0_iter7_reg <= icmp_ln338_reg_1200_pp0_iter6_reg;
        icmp_ln338_reg_1200_pp0_iter8_reg <= icmp_ln338_reg_1200_pp0_iter7_reg;
        icmp_ln338_reg_1200_pp0_iter9_reg <= icmp_ln338_reg_1200_pp0_iter8_reg;
        m_diff_hi_V_reg_1230 <= {{m_diff_V_fu_579_p2[58:51]}};
        m_diff_hi_V_reg_1230_pp0_iter6_reg <= m_diff_hi_V_reg_1230;
        m_diff_hi_V_reg_1230_pp0_iter7_reg <= m_diff_hi_V_reg_1230_pp0_iter6_reg;
        m_diff_hi_V_reg_1230_pp0_iter8_reg <= m_diff_hi_V_reg_1230_pp0_iter7_reg;
        p_Result_9_reg_1160_pp0_iter10_reg <= p_Result_9_reg_1160_pp0_iter9_reg;
        p_Result_9_reg_1160_pp0_iter2_reg <= p_Result_9_reg_1160_pp0_iter1_reg;
        p_Result_9_reg_1160_pp0_iter3_reg <= p_Result_9_reg_1160_pp0_iter2_reg;
        p_Result_9_reg_1160_pp0_iter4_reg <= p_Result_9_reg_1160_pp0_iter3_reg;
        p_Result_9_reg_1160_pp0_iter5_reg <= p_Result_9_reg_1160_pp0_iter4_reg;
        p_Result_9_reg_1160_pp0_iter6_reg <= p_Result_9_reg_1160_pp0_iter5_reg;
        p_Result_9_reg_1160_pp0_iter7_reg <= p_Result_9_reg_1160_pp0_iter6_reg;
        p_Result_9_reg_1160_pp0_iter8_reg <= p_Result_9_reg_1160_pp0_iter7_reg;
        p_Result_9_reg_1160_pp0_iter9_reg <= p_Result_9_reg_1160_pp0_iter8_reg;
        r_V_15_reg_1318 <= r_V_15_fu_829_p2;
        ret_V_10_reg_1273[25 : 0] <= ret_V_10_fu_661_p4[25 : 0];
ret_V_10_reg_1273[42 : 35] <= ret_V_10_fu_661_p4[42 : 35];
        ret_V_11_reg_1313 <= ret_V_11_fu_816_p2;
        ret_V_8_reg_1218 <= ret_V_8_fu_545_p3;
        ret_V_8_reg_1218_pp0_iter10_reg <= ret_V_8_reg_1218_pp0_iter9_reg;
        ret_V_8_reg_1218_pp0_iter4_reg <= ret_V_8_reg_1218;
        ret_V_8_reg_1218_pp0_iter5_reg <= ret_V_8_reg_1218_pp0_iter4_reg;
        ret_V_8_reg_1218_pp0_iter6_reg <= ret_V_8_reg_1218_pp0_iter5_reg;
        ret_V_8_reg_1218_pp0_iter7_reg <= ret_V_8_reg_1218_pp0_iter6_reg;
        ret_V_8_reg_1218_pp0_iter8_reg <= ret_V_8_reg_1218_pp0_iter7_reg;
        ret_V_8_reg_1218_pp0_iter9_reg <= ret_V_8_reg_1218_pp0_iter8_reg;
        ret_V_9_reg_1262 <= ret_V_9_fu_655_p2;
        select_ln253_reg_1180_pp0_iter10_reg <= select_ln253_reg_1180_pp0_iter9_reg;
        select_ln253_reg_1180_pp0_iter2_reg <= select_ln253_reg_1180_pp0_iter1_reg;
        select_ln253_reg_1180_pp0_iter3_reg <= select_ln253_reg_1180_pp0_iter2_reg;
        select_ln253_reg_1180_pp0_iter4_reg <= select_ln253_reg_1180_pp0_iter3_reg;
        select_ln253_reg_1180_pp0_iter5_reg <= select_ln253_reg_1180_pp0_iter4_reg;
        select_ln253_reg_1180_pp0_iter6_reg <= select_ln253_reg_1180_pp0_iter5_reg;
        select_ln253_reg_1180_pp0_iter7_reg <= select_ln253_reg_1180_pp0_iter6_reg;
        select_ln253_reg_1180_pp0_iter8_reg <= select_ln253_reg_1180_pp0_iter7_reg;
        select_ln253_reg_1180_pp0_iter9_reg <= select_ln253_reg_1180_pp0_iter8_reg;
        tmp_2_reg_1225 <= {{r_V_8_fu_556_p2[70:13]}};
        tmp_3_reg_1293 <= {{table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0[41:2]}};
        trunc_ln657_5_reg_1298 <= {{r_V_11_fu_744_p2[92:57]}};
        trunc_ln657_reg_1195_pp0_iter2_reg <= trunc_ln657_reg_1195_pp0_iter1_reg;
        trunc_ln657_reg_1195_pp0_iter3_reg <= trunc_ln657_reg_1195_pp0_iter2_reg;
        trunc_ln657_reg_1195_pp0_iter4_reg <= trunc_ln657_reg_1195_pp0_iter3_reg;
        x_is_NaN_reg_1165_pp0_iter10_reg <= x_is_NaN_reg_1165_pp0_iter9_reg;
        x_is_NaN_reg_1165_pp0_iter2_reg <= x_is_NaN_reg_1165_pp0_iter1_reg;
        x_is_NaN_reg_1165_pp0_iter3_reg <= x_is_NaN_reg_1165_pp0_iter2_reg;
        x_is_NaN_reg_1165_pp0_iter4_reg <= x_is_NaN_reg_1165_pp0_iter3_reg;
        x_is_NaN_reg_1165_pp0_iter5_reg <= x_is_NaN_reg_1165_pp0_iter4_reg;
        x_is_NaN_reg_1165_pp0_iter6_reg <= x_is_NaN_reg_1165_pp0_iter5_reg;
        x_is_NaN_reg_1165_pp0_iter7_reg <= x_is_NaN_reg_1165_pp0_iter6_reg;
        x_is_NaN_reg_1165_pp0_iter8_reg <= x_is_NaN_reg_1165_pp0_iter7_reg;
        x_is_NaN_reg_1165_pp0_iter9_reg <= x_is_NaN_reg_1165_pp0_iter8_reg;
        x_is_inf_reg_1173_pp0_iter10_reg <= x_is_inf_reg_1173_pp0_iter9_reg;
        x_is_inf_reg_1173_pp0_iter2_reg <= x_is_inf_reg_1173_pp0_iter1_reg;
        x_is_inf_reg_1173_pp0_iter3_reg <= x_is_inf_reg_1173_pp0_iter2_reg;
        x_is_inf_reg_1173_pp0_iter4_reg <= x_is_inf_reg_1173_pp0_iter3_reg;
        x_is_inf_reg_1173_pp0_iter5_reg <= x_is_inf_reg_1173_pp0_iter4_reg;
        x_is_inf_reg_1173_pp0_iter6_reg <= x_is_inf_reg_1173_pp0_iter5_reg;
        x_is_inf_reg_1173_pp0_iter7_reg <= x_is_inf_reg_1173_pp0_iter6_reg;
        x_is_inf_reg_1173_pp0_iter8_reg <= x_is_inf_reg_1173_pp0_iter7_reg;
        x_is_inf_reg_1173_pp0_iter9_reg <= x_is_inf_reg_1173_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        f_Z3_reg_1268 <= table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1453_reg_1208 <= icmp_ln1453_fu_489_p2;
        icmp_ln1453_reg_1208_pp0_iter1_reg <= icmp_ln1453_reg_1208;
        icmp_ln338_reg_1200 <= icmp_ln338_fu_467_p2;
        icmp_ln338_reg_1200_pp0_iter1_reg <= icmp_ln338_reg_1200;
        p_Result_11_reg_1185 <= r_V_13_fu_407_p3[32'd70];
        p_Result_11_reg_1185_pp0_iter1_reg <= p_Result_11_reg_1185;
        p_Result_9_reg_1160 <= data_V_fu_261_p1[32'd63];
        p_Result_9_reg_1160_pp0_iter1_reg <= p_Result_9_reg_1160;
        select_ln253_reg_1180 <= select_ln253_fu_341_p3;
        select_ln253_reg_1180_pp0_iter1_reg <= select_ln253_reg_1180;
        trunc_ln657_reg_1195 <= trunc_ln657_fu_463_p1;
        trunc_ln657_reg_1195_pp0_iter1_reg <= trunc_ln657_reg_1195;
        x_is_NaN_reg_1165 <= x_is_NaN_fu_299_p2;
        x_is_NaN_reg_1165_pp0_iter1_reg <= x_is_NaN_reg_1165;
        x_is_inf_reg_1173 <= x_is_inf_fu_311_p2;
        x_is_inf_reg_1173_pp0_iter1_reg <= x_is_inf_reg_1173;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (x_is_NaN_reg_1165_pp0_iter9_reg == 1'd0))) begin
        trunc_ln1146_2_reg_1330 <= trunc_ln1146_2_fu_839_p1;
        trunc_ln1146_reg_1325 <= trunc_ln1146_fu_835_p1;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to10 = 1'b1;
    end else begin
        ap_idle_pp0_0to10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Z3_V_fu_604_p4 = {{m_diff_V_fu_579_p2[42:35]}};

assign Z4_fu_614_p1 = m_diff_V_fu_579_p2[34:0];

assign Z4_ind_fu_618_p4 = {{m_diff_V_fu_579_p2[34:27]}};

assign add_ln1146_1_fu_902_p2 = (trunc_ln1146_1_fu_889_p3 + zext_ln1146_4_fu_886_p1);

assign add_ln1146_2_fu_908_p2 = (trunc_ln2_fu_879_p3 + zext_ln1146_3_fu_876_p1);

assign add_ln657_2_fu_781_p2 = (exp_Z2P_m_1_V_reg_1288 + zext_ln657_4_fu_778_p1);

assign add_ln657_fu_696_p2 = (ret_V_9_reg_1262 + zext_ln657_2_fu_692_p1);

assign and_ln18_fu_1088_p2 = (xor_ln18_1_fu_1083_p2 & x_is_inf_reg_1173_pp0_iter10_reg);

assign and_ln338_1_fu_1107_p2 = (xor_ln338_1_fu_1101_p2 & icmp_ln338_reg_1200_pp0_iter10_reg);

assign and_ln338_fu_1040_p2 = (or_ln338_fu_950_p2 & icmp_ln338_reg_1200_pp0_iter10_reg);

assign and_ln840_fu_1050_p2 = (xor_ln338_fu_1045_p2 & icmp_ln840_fu_944_p2);

assign and_ln_fu_572_p3 = {{tmp_2_reg_1225}, {1'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = ((sel_tmp23_fu_1135_p2[0:0] == 1'b1) ? 64'd0 : select_ln18_1_fu_1093_p3);

assign bitcast_ln521_fu_1026_p1 = zext_ln368_fu_1022_p1;

assign data_V_fu_261_p1 = x;

assign e_frac_V_1_fu_335_p2 = (54'd0 - p_Result_10_fu_327_p3);

assign exp_Z1P_m_1_l_V_fu_790_p2 = (zext_ln657_5_fu_786_p1 + zext_ln1146_1_fu_774_p1);

assign exp_Z1_hi_V_fu_806_p4 = {{table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0[57:8]}};

assign exp_Z2P_m_1_V_fu_711_p2 = (zext_ln657_3_fu_708_p1 + zext_ln1146_fu_705_p1);

assign exp_Z2_m_1_V_fu_727_p4 = {{{Z2_V_reg_1235_pp0_iter7_reg}, {1'd0}}, {tmp_3_fu_717_p4}};

assign grp_fu_1149_p1 = 31'd23637;

assign icmp_ln1453_fu_489_p2 = ((shl_ln_fu_481_p3 != sext_ln256_fu_357_p1) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_293_p2 = ((tmp_21_fu_283_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln209_fu_287_p2 = ((tmp_20_fu_273_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln338_fu_467_p2 = (($signed(m_exp_fu_321_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln805_fu_525_p2 = ((trunc_ln805_fu_522_p1 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln824_fu_305_p2 = ((tmp_21_fu_283_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln840_fu_944_p2 = (($signed(tmp_17_fu_934_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln844_fu_970_p2 = (($signed(r_exp_V_2_fu_927_p3) < $signed(13'd7170)) ? 1'b1 : 1'b0);

assign isNeg_fu_361_p3 = m_exp_fu_321_p2[32'd11];

assign lhs_V_3_fu_866_p3 = {{ret_V_11_reg_1313}, {49'd0}};

assign lhs_V_fu_764_p5 = {{{{Z2_V_reg_1235_pp0_iter8_reg}, {1'd0}}, {tmp_3_reg_1293}}, {2'd0}};

assign m_diff_V_fu_579_p2 = (trunc_ln657_reg_1195_pp0_iter4_reg - and_ln_fu_572_p3);

assign m_exp_fu_321_p2 = ($signed(zext_ln510_fu_317_p1) + $signed(12'd3073));

assign m_fix_hi_fu_441_p4 = {{r_V_13_fu_407_p3[70:55]}};

assign m_fix_l_fu_415_p4 = {{r_V_13_fu_407_p3[70:7]}};

assign m_frac_l_V_fu_349_p3 = {{select_ln253_fu_341_p3}, {7'd0}};

assign or_ln18_fu_1030_p2 = (x_is_inf_reg_1173_pp0_iter10_reg | x_is_NaN_reg_1165_pp0_iter10_reg);

assign or_ln214_fu_853_p2 = (x_is_pinf_fu_848_p2 | x_is_NaN_reg_1165_pp0_iter10_reg);

assign or_ln338_fu_950_p2 = (icmp_ln840_fu_944_p2 | icmp_ln1453_reg_1208_pp0_iter10_reg);

assign or_ln840_1_fu_1112_p2 = (icmp_ln840_fu_944_p2 | icmp_ln338_reg_1200_pp0_iter10_reg);

assign or_ln840_2_fu_1123_p2 = (xor_ln840_fu_1117_p2 | and_ln338_1_fu_1107_p2);

assign or_ln840_fu_1056_p2 = (and_ln840_fu_1050_p2 | and_ln338_fu_1040_p2);

assign out_exp_V_fu_1008_p2 = (trunc_ln167_fu_1004_p1 + 11'd1023);

assign p_Result_10_fu_327_p3 = {{2'd1}, {tmp_21_fu_283_p1}};

assign p_Result_12_fu_1014_p3 = {{out_exp_V_fu_1008_p2}, {tmp_22_fu_996_p3}};

assign p_Result_9_fu_265_p3 = data_V_fu_261_p1[32'd63];

assign p_Result_s_fu_515_p3 = grp_fu_1149_p3[32'd30];

assign r_V_10_fu_676_p0 = r_V_10_fu_676_p00;

assign r_V_10_fu_676_p00 = ret_V_10_fu_661_p4;

assign r_V_10_fu_676_p1 = r_V_10_fu_676_p10;

assign r_V_10_fu_676_p10 = ret_V_9_reg_1262;

assign r_V_11_fu_744_p0 = r_V_11_fu_744_p00;

assign r_V_11_fu_744_p00 = exp_Z2_m_1_V_fu_727_p4;

assign r_V_11_fu_744_p1 = r_V_11_fu_744_p10;

assign r_V_11_fu_744_p10 = exp_Z2P_m_1_V_fu_711_p2;

assign r_V_13_fu_407_p3 = ((isNeg_fu_361_p3[0:0] == 1'b1) ? r_V_fu_395_p2 : r_V_1_fu_401_p2);

assign r_V_15_fu_829_p0 = r_V_15_fu_829_p00;

assign r_V_15_fu_829_p00 = exp_Z1P_m_1_V_reg_1308;

assign r_V_15_fu_829_p1 = r_V_15_fu_829_p10;

assign r_V_15_fu_829_p10 = exp_Z1_hi_V_fu_806_p4;

assign r_V_1_fu_401_p2 = sext_ln256_fu_357_p1 << sh_prom_i_i360_cast_cast_cast_cast_fu_391_p1;

assign r_V_3_fu_429_p2 = m_fix_l_fu_415_p4 << sh_prom_i_i340_cast_cast_cast_cast_fu_425_p1;

assign r_V_4_fu_435_p2 = $signed(m_fix_l_fu_415_p4) >>> sh_prom_i_i340_cast_cast_cast_cast_fu_425_p1;

assign r_V_fu_395_p2 = $signed(sext_ln256_fu_357_p1) >>> sh_prom_i_i360_cast_cast_cast_cast_fu_391_p1;

assign r_exp_V_2_fu_927_p3 = ((tmp_16_fu_914_p3[0:0] == 1'b1) ? ret_V_8_reg_1218_pp0_iter10_reg : r_exp_V_fu_922_p2);

assign r_exp_V_fu_922_p2 = ($signed(ret_V_8_reg_1218_pp0_iter10_reg) + $signed(13'd8191));

assign r_fu_638_p4 = {{table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1[25:16]}};

assign ret_V_10_fu_661_p4 = {{{Z3_V_reg_1242_pp0_iter6_reg}, {9'd0}}, {f_Z3_reg_1268}};

assign ret_V_11_fu_816_p2 = (table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0 + 58'd16);

assign ret_V_6_fu_896_p2 = (lhs_V_3_fu_866_p3 + zext_ln1146_2_fu_873_p1);

assign ret_V_8_fu_545_p3 = ((p_Result_s_fu_515_p3[0:0] == 1'b1) ? select_ln804_fu_537_p3 : ret_V_cast_fu_506_p4);

assign ret_V_9_fu_655_p2 = (zext_ln657_fu_648_p1 + zext_ln657_1_fu_651_p1);

assign ret_V_cast_fu_506_p4 = {{grp_fu_1149_p3[30:18]}};

assign ret_V_fu_531_p2 = (ret_V_cast_fu_506_p4 + 13'd1);

assign rhs_fu_495_p3 = {{p_Result_11_reg_1185_pp0_iter1_reg}, {18'd131072}};

assign sel_tmp23_fu_1135_p2 = (tmp27_fu_1129_p2 & icmp_ln844_fu_970_p2);

assign sel_tmp7_fu_1062_p2 = (xor_ln18_fu_1034_p2 & or_ln840_fu_1056_p2);

assign sel_tmp8_fu_1068_p3 = ((sel_tmp7_fu_1062_p2[0:0] == 1'b1) ? select_ln344_fu_962_p3 : bitcast_ln521_fu_1026_p1);

assign select_ln1322_fu_473_p3 = ((isNeg_fu_361_p3[0:0] == 1'b1) ? r_V_3_fu_429_p2 : r_V_4_fu_435_p2);

assign select_ln18_1_fu_1093_p3 = ((and_ln18_fu_1088_p2[0:0] == 1'b1) ? select_ln214_fu_858_p3 : select_ln18_fu_1076_p3);

assign select_ln18_fu_1076_p3 = ((x_is_NaN_reg_1165_pp0_iter10_reg[0:0] == 1'b1) ? 64'd9223372036854775807 : sel_tmp8_fu_1068_p3);

assign select_ln214_fu_858_p3 = ((or_ln214_fu_853_p2[0:0] == 1'b1) ? 64'd9218868437227405312 : 64'd0);

assign select_ln253_fu_341_p3 = ((p_Result_9_fu_265_p3[0:0] == 1'b1) ? e_frac_V_1_fu_335_p2 : p_Result_10_fu_327_p3);

assign select_ln344_fu_962_p3 = ((tmp_18_fu_955_p3[0:0] == 1'b1) ? 64'd0 : 64'd9218868437227405312);

assign select_ln804_fu_537_p3 = ((icmp_ln805_fu_525_p2[0:0] == 1'b1) ? ret_V_cast_fu_506_p4 : ret_V_fu_531_p2);

assign sext_ln1311_fu_375_p1 = $signed(sub_ln1311_fu_369_p2);

assign sext_ln256_fu_357_p1 = $signed(m_frac_l_V_fu_349_p3);

assign sh_prom_i_i340_cast_cast_cast_cast_fu_425_p1 = $unsigned(sh_prom_i_i360_cast_cast_cast_fu_387_p1);

assign sh_prom_i_i360_cast_cast_cast_cast_fu_391_p1 = $unsigned(sh_prom_i_i360_cast_cast_cast_fu_387_p1);

assign sh_prom_i_i360_cast_cast_cast_fu_387_p1 = $signed(ush_fu_379_p3);

assign shl_ln_fu_481_p3 = {{select_ln1322_fu_473_p3}, {7'd0}};

assign sub_ln1311_fu_369_p2 = (11'd1023 - tmp_20_fu_273_p4);

assign table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln488_fu_760_p1;

assign table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln488_3_fu_701_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln488_2_fu_633_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1 = zext_ln488_1_fu_628_p1;

assign tmp27_fu_1129_p2 = (xor_ln18_fu_1034_p2 & or_ln840_2_fu_1123_p2);

assign tmp_16_fu_914_p3 = ret_V_6_fu_896_p2[32'd106];

assign tmp_17_fu_934_p4 = {{r_exp_V_2_fu_927_p3[12:10]}};

assign tmp_18_fu_955_p3 = select_ln253_reg_1180_pp0_iter10_reg[32'd53];

assign tmp_20_fu_273_p4 = {{data_V_fu_261_p1[62:52]}};

assign tmp_21_fu_283_p1 = data_V_fu_261_p1[51:0];

assign tmp_22_fu_996_p3 = ((tmp_16_fu_914_p3[0:0] == 1'b1) ? tmp_fu_976_p4 : tmp_s_fu_986_p4);

assign tmp_3_fu_717_p4 = {{table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0[41:2]}};

assign tmp_fu_976_p4 = {{add_ln1146_2_fu_908_p2[105:54]}};

assign tmp_s_fu_986_p4 = {{add_ln1146_1_fu_902_p2[104:53]}};

assign trunc_ln1146_1_fu_889_p3 = {{trunc_ln1146_2_reg_1330}, {49'd0}};

assign trunc_ln1146_2_fu_839_p1 = ret_V_11_fu_816_p2[55:0];

assign trunc_ln1146_fu_835_p1 = ret_V_11_fu_816_p2[56:0];

assign trunc_ln167_fu_1004_p1 = r_exp_V_2_fu_927_p3[10:0];

assign trunc_ln2_fu_879_p3 = {{trunc_ln1146_reg_1325}, {49'd0}};

assign trunc_ln657_4_fu_682_p4 = {{r_V_10_fu_676_p2[78:59]}};

assign trunc_ln657_fu_463_p1 = r_V_13_fu_407_p3[58:0];

assign trunc_ln805_fu_522_p1 = grp_fu_1149_p3[17:0];

assign ush_fu_379_p3 = ((isNeg_fu_361_p3[0:0] == 1'b1) ? sext_ln1311_fu_375_p1 : m_exp_fu_321_p2);

assign x_is_NaN_fu_299_p2 = (icmp_ln209_fu_287_p2 & icmp_ln18_fu_293_p2);

assign x_is_inf_fu_311_p2 = (icmp_ln824_fu_305_p2 & icmp_ln209_fu_287_p2);

assign x_is_pinf_fu_848_p2 = (xor_ln964_fu_843_p2 & x_is_inf_reg_1173_pp0_iter10_reg);

assign xor_ln18_1_fu_1083_p2 = (x_is_NaN_reg_1165_pp0_iter10_reg ^ 1'd1);

assign xor_ln18_fu_1034_p2 = (or_ln18_fu_1030_p2 ^ 1'd1);

assign xor_ln338_1_fu_1101_p2 = (or_ln338_fu_950_p2 ^ 1'd1);

assign xor_ln338_fu_1045_p2 = (icmp_ln338_reg_1200_pp0_iter10_reg ^ 1'd1);

assign xor_ln840_fu_1117_p2 = (or_ln840_1_fu_1112_p2 ^ 1'd1);

assign xor_ln964_fu_843_p2 = (p_Result_9_reg_1160_pp0_iter10_reg ^ 1'd1);

assign zext_ln1146_1_fu_774_p1 = lhs_V_fu_764_p5;

assign zext_ln1146_2_fu_873_p1 = r_V_15_reg_1318;

assign zext_ln1146_3_fu_876_p1 = r_V_15_reg_1318;

assign zext_ln1146_4_fu_886_p1 = r_V_15_reg_1318;

assign zext_ln1146_fu_705_p1 = ret_V_10_reg_1273;

assign zext_ln368_fu_1022_p1 = p_Result_12_fu_1014_p3;

assign zext_ln488_1_fu_628_p1 = Z4_ind_fu_618_p4;

assign zext_ln488_2_fu_633_p1 = Z3_V_fu_604_p4;

assign zext_ln488_3_fu_701_p1 = Z2_V_reg_1235_pp0_iter6_reg;

assign zext_ln488_fu_760_p1 = m_diff_hi_V_reg_1230_pp0_iter8_reg;

assign zext_ln510_fu_317_p1 = tmp_20_fu_273_p4;

assign zext_ln657_1_fu_651_p1 = r_fu_638_p4;

assign zext_ln657_2_fu_692_p1 = trunc_ln657_4_fu_682_p4;

assign zext_ln657_3_fu_708_p1 = add_ln657_reg_1278;

assign zext_ln657_4_fu_778_p1 = trunc_ln657_5_reg_1298;

assign zext_ln657_5_fu_786_p1 = add_ln657_2_fu_781_p2;

assign zext_ln657_fu_648_p1 = Z4_reg_1247;

always @ (posedge ap_clk) begin
    ret_V_10_reg_1273[34:26] <= 9'b000000000;
end

endmodule //l3_exp_generic_double_s
