// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calculateLayer34_calculateLayer34,hls_ip_2020_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=15.041994,HLS_SYN_LAT=187817,HLS_SYN_TPT=none,HLS_SYN_MEM=1049,HLS_SYN_DSP=0,HLS_SYN_FF=32343,HLS_SYN_LUT=35429,HLS_VERSION=2020_2}" *)

module calculateLayer34 (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] Layer2_Neurons_CPU;
wire   [63:0] Layer4_Neurons_CPU;
reg   [31:0] Layer3_Neurons_CPU_622_1;
reg   [31:0] Layer3_Neurons_CPU_623_0;
reg   [31:0] Layer3_Neurons_CPU_623_1;
reg   [31:0] Layer3_Neurons_CPU_624_0;
reg   [31:0] Layer3_Neurons_CPU_624_1;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [31:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
reg    gmem1_AWVALID;
wire    gmem1_AWREADY;
reg    gmem1_WVALID;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [31:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
reg    gmem1_BREADY;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
reg   [63:0] Layer4_Neurons_CPU_read_reg_137;
reg   [63:0] Layer2_Neurons_CPU_read_reg_142;
wire    grp_calculateLayer3_301_302_1_fu_86_ap_start;
wire    grp_calculateLayer3_301_302_1_fu_86_ap_done;
wire    grp_calculateLayer3_301_302_1_fu_86_ap_idle;
wire    grp_calculateLayer3_301_302_1_fu_86_ap_ready;
wire    grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWVALID;
wire   [63:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWADDR;
wire   [0:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWID;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWLEN;
wire   [2:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWBURST;
wire   [1:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWPROT;
wire   [3:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWQOS;
wire   [3:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWREGION;
wire   [0:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWUSER;
wire    grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WVALID;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WDATA;
wire   [3:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WSTRB;
wire    grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WLAST;
wire   [0:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WID;
wire   [0:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WUSER;
wire    grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARVALID;
wire   [63:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARADDR;
wire   [0:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARID;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARLEN;
wire   [2:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARBURST;
wire   [1:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARPROT;
wire   [3:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARQOS;
wire   [3:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARREGION;
wire   [0:0] grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARUSER;
wire    grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_RREADY;
wire    grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_BREADY;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_622_1;
wire    grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_622_1_ap_vld;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_0;
wire    grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_0_ap_vld;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_1;
wire    grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_1_ap_vld;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_0;
wire    grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_0_ap_vld;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_1;
wire    grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_1_ap_vld;
wire   [63:0] grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_din1;
wire   [63:0] grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_dout0;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_ce;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_start;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_ready;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_done;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_idle;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_din0;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_din1;
wire   [1:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_opcode;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_dout0;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_ce;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_din0;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_din1;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_dout0;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_ce;
wire   [63:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_din0;
wire   [31:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_dout0;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_ce;
wire   [63:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_din0;
wire   [63:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_din1;
wire   [63:0] grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_dout0;
wire    grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_ce;
wire    grp_calculateLayer4_1_fu_112_ap_start;
wire    grp_calculateLayer4_1_fu_112_ap_done;
wire    grp_calculateLayer4_1_fu_112_ap_idle;
wire    grp_calculateLayer4_1_fu_112_ap_ready;
wire    grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWVALID;
wire   [63:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWADDR;
wire   [0:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWID;
wire   [31:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWLEN;
wire   [2:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWBURST;
wire   [1:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWPROT;
wire   [3:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWQOS;
wire   [3:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWREGION;
wire   [0:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWUSER;
wire    grp_calculateLayer4_1_fu_112_m_axi_gmem1_WVALID;
wire   [31:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_WDATA;
wire   [3:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_WSTRB;
wire    grp_calculateLayer4_1_fu_112_m_axi_gmem1_WLAST;
wire   [0:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_WID;
wire   [0:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_WUSER;
wire    grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARVALID;
wire   [63:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARADDR;
wire   [0:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARID;
wire   [31:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARLEN;
wire   [2:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARBURST;
wire   [1:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARPROT;
wire   [3:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARQOS;
wire   [3:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARREGION;
wire   [0:0] grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARUSER;
wire    grp_calculateLayer4_1_fu_112_m_axi_gmem1_RREADY;
wire    grp_calculateLayer4_1_fu_112_m_axi_gmem1_BREADY;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_din1;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_ce;
wire    grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_start;
wire    grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_ready;
wire    grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_done;
wire    grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_idle;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_154_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_154_p_din1;
wire   [1:0] grp_calculateLayer4_1_fu_112_grp_fu_154_p_opcode;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_154_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_154_p_ce;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_169_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_169_p_din1;
wire   [1:0] grp_calculateLayer4_1_fu_112_grp_fu_169_p_opcode;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_169_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_169_p_ce;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_173_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_173_p_din1;
wire   [1:0] grp_calculateLayer4_1_fu_112_grp_fu_173_p_opcode;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_173_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_173_p_ce;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_177_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_177_p_din1;
wire   [1:0] grp_calculateLayer4_1_fu_112_grp_fu_177_p_opcode;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_177_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_177_p_ce;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_158_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_158_p_din1;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_158_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_158_p_ce;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_181_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_181_p_din1;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_181_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_181_p_ce;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_185_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_185_p_din1;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_185_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_185_p_ce;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_189_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_189_p_din1;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_189_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_189_p_ce;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_193_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_193_p_din1;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_193_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_193_p_ce;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_fu_162_p_din0;
wire   [31:0] grp_calculateLayer4_1_fu_112_grp_fu_162_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_162_p_ce;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_fu_165_p_din0;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_fu_165_p_din1;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_fu_165_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_165_p_ce;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_fu_197_p_din0;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_fu_197_p_din1;
wire   [63:0] grp_calculateLayer4_1_fu_112_grp_fu_197_p_dout0;
wire    grp_calculateLayer4_1_fu_112_grp_fu_197_p_ce;
reg    grp_generic_tanh_double_s_fu_147_ap_start;
wire    grp_generic_tanh_double_s_fu_147_ap_done;
wire    grp_generic_tanh_double_s_fu_147_ap_idle;
wire    grp_generic_tanh_double_s_fu_147_ap_ready;
reg    grp_generic_tanh_double_s_fu_147_ap_ce;
reg   [63:0] grp_generic_tanh_double_s_fu_147_t_in;
wire   [63:0] grp_generic_tanh_double_s_fu_147_ap_return;
reg    grp_calculateLayer3_301_302_1_fu_86_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_calculateLayer4_1_fu_112_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [31:0] grp_fu_154_p2;
reg   [31:0] grp_fu_154_p0;
reg   [31:0] grp_fu_154_p1;
reg    grp_fu_154_ce;
wire   [31:0] grp_fu_158_p2;
reg   [31:0] grp_fu_158_p0;
reg   [31:0] grp_fu_158_p1;
reg    grp_fu_158_ce;
wire   [31:0] grp_fu_162_p1;
reg   [63:0] grp_fu_162_p0;
reg    grp_fu_162_ce;
wire   [63:0] grp_fu_165_p2;
reg   [63:0] grp_fu_165_p0;
reg   [63:0] grp_fu_165_p1;
reg    grp_fu_165_ce;
wire   [31:0] grp_fu_169_p2;
wire   [31:0] grp_fu_169_p0;
wire   [31:0] grp_fu_169_p1;
reg    grp_fu_169_ce;
wire   [31:0] grp_fu_173_p2;
wire   [31:0] grp_fu_173_p0;
wire   [31:0] grp_fu_173_p1;
reg    grp_fu_173_ce;
wire   [31:0] grp_fu_177_p2;
wire   [31:0] grp_fu_177_p0;
wire   [31:0] grp_fu_177_p1;
reg    grp_fu_177_ce;
wire   [31:0] grp_fu_181_p2;
wire   [31:0] grp_fu_181_p0;
wire   [31:0] grp_fu_181_p1;
reg    grp_fu_181_ce;
wire   [31:0] grp_fu_185_p2;
wire   [31:0] grp_fu_185_p0;
wire   [31:0] grp_fu_185_p1;
reg    grp_fu_185_ce;
wire   [31:0] grp_fu_189_p2;
wire   [31:0] grp_fu_189_p0;
wire   [31:0] grp_fu_189_p1;
reg    grp_fu_189_ce;
wire   [31:0] grp_fu_193_p2;
wire   [31:0] grp_fu_193_p0;
wire   [31:0] grp_fu_193_p1;
reg    grp_fu_193_ce;
wire   [63:0] grp_fu_197_p2;
wire   [63:0] grp_fu_197_p0;
wire   [63:0] grp_fu_197_p1;
reg    grp_fu_197_ce;
reg   [3:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 Layer3_Neurons_CPU_622_1 = 32'd0;
#0 Layer3_Neurons_CPU_623_0 = 32'd0;
#0 Layer3_Neurons_CPU_623_1 = 32'd0;
#0 Layer3_Neurons_CPU_624_0 = 32'd0;
#0 Layer3_Neurons_CPU_624_1 = 32'd0;
#0 grp_calculateLayer3_301_302_1_fu_86_ap_start_reg = 1'b0;
#0 grp_calculateLayer4_1_fu_112_ap_start_reg = 1'b0;
end

calculateLayer34_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .Layer2_Neurons_CPU(Layer2_Neurons_CPU),
    .Layer4_Neurons_CPU(Layer4_Neurons_CPU),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

calculateLayer34_gmem0_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARADDR),
    .I_ARID(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARID),
    .I_ARLEN(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARLEN),
    .I_ARSIZE(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARSIZE),
    .I_ARLOCK(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARLOCK),
    .I_ARCACHE(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARCACHE),
    .I_ARQOS(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARQOS),
    .I_ARPROT(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARPROT),
    .I_ARUSER(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARUSER),
    .I_ARBURST(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARBURST),
    .I_ARREGION(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARREGION),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RID(gmem0_RID),
    .I_RUSER(gmem0_RUSER),
    .I_RRESP(gmem0_RRESP),
    .I_RLAST(gmem0_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem0_BRESP),
    .I_BID(gmem0_BID),
    .I_BUSER(gmem0_BUSER)
);

calculateLayer34_gmem1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(gmem1_AWVALID),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWADDR),
    .I_AWID(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWID),
    .I_AWLEN(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWLEN),
    .I_AWSIZE(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWSIZE),
    .I_AWLOCK(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWLOCK),
    .I_AWCACHE(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWCACHE),
    .I_AWQOS(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWQOS),
    .I_AWPROT(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWPROT),
    .I_AWUSER(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWUSER),
    .I_AWBURST(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWBURST),
    .I_AWREGION(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWREGION),
    .I_WVALID(gmem1_WVALID),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WDATA),
    .I_WID(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WID),
    .I_WUSER(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WUSER),
    .I_WLAST(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WLAST),
    .I_WSTRB(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WSTRB),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(gmem1_BREADY),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

calculateLayer34_calculateLayer3_301_302_1 grp_calculateLayer3_301_302_1_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_calculateLayer3_301_302_1_fu_86_ap_start),
    .ap_done(grp_calculateLayer3_301_302_1_fu_86_ap_done),
    .ap_idle(grp_calculateLayer3_301_302_1_fu_86_ap_idle),
    .ap_ready(grp_calculateLayer3_301_302_1_fu_86_ap_ready),
    .m_axi_gmem0_AWVALID(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(gmem0_RLAST),
    .m_axi_gmem0_RID(gmem0_RID),
    .m_axi_gmem0_RUSER(gmem0_RUSER),
    .m_axi_gmem0_RRESP(gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .Layer2_Neurons_CPU(Layer2_Neurons_CPU_read_reg_142),
    .Layer3_Neurons_CPU_622_1(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_622_1),
    .Layer3_Neurons_CPU_622_1_ap_vld(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_622_1_ap_vld),
    .Layer3_Neurons_CPU_623_0(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_0),
    .Layer3_Neurons_CPU_623_0_ap_vld(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_0_ap_vld),
    .Layer3_Neurons_CPU_623_1(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_1),
    .Layer3_Neurons_CPU_623_1_ap_vld(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_1_ap_vld),
    .Layer3_Neurons_CPU_624_0(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_0),
    .Layer3_Neurons_CPU_624_0_ap_vld(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_0_ap_vld),
    .Layer3_Neurons_CPU_624_1(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_1),
    .Layer3_Neurons_CPU_624_1_ap_vld(grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_1_ap_vld),
    .grp_generic_tanh_double_s_fu_147_p_din1(grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_din1),
    .grp_generic_tanh_double_s_fu_147_p_dout0(grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_dout0),
    .grp_generic_tanh_double_s_fu_147_p_ce(grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_ce),
    .grp_generic_tanh_double_s_fu_147_p_start(grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_start),
    .grp_generic_tanh_double_s_fu_147_p_ready(grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_ready),
    .grp_generic_tanh_double_s_fu_147_p_done(grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_done),
    .grp_generic_tanh_double_s_fu_147_p_idle(grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_idle),
    .grp_fu_154_p_din0(grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_din0),
    .grp_fu_154_p_din1(grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_din1),
    .grp_fu_154_p_opcode(grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_opcode),
    .grp_fu_154_p_dout0(grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_dout0),
    .grp_fu_154_p_ce(grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_ce),
    .grp_fu_158_p_din0(grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_din0),
    .grp_fu_158_p_din1(grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_din1),
    .grp_fu_158_p_dout0(grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_dout0),
    .grp_fu_158_p_ce(grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_ce),
    .grp_fu_162_p_din0(grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_din0),
    .grp_fu_162_p_dout0(grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_dout0),
    .grp_fu_162_p_ce(grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_ce),
    .grp_fu_165_p_din0(grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_din0),
    .grp_fu_165_p_din1(grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_din1),
    .grp_fu_165_p_dout0(grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_dout0),
    .grp_fu_165_p_ce(grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_ce)
);

calculateLayer34_calculateLayer4_1 grp_calculateLayer4_1_fu_112(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_calculateLayer4_1_fu_112_ap_start),
    .ap_done(grp_calculateLayer4_1_fu_112_ap_done),
    .ap_idle(grp_calculateLayer4_1_fu_112_ap_idle),
    .ap_ready(grp_calculateLayer4_1_fu_112_ap_ready),
    .m_axi_gmem1_AWVALID(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(gmem1_WREADY),
    .m_axi_gmem1_WDATA(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_calculateLayer4_1_fu_112_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_calculateLayer4_1_fu_112_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(grp_calculateLayer4_1_fu_112_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(32'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(gmem1_BVALID),
    .m_axi_gmem1_BREADY(grp_calculateLayer4_1_fu_112_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(gmem1_BRESP),
    .m_axi_gmem1_BID(gmem1_BID),
    .m_axi_gmem1_BUSER(gmem1_BUSER),
    .Layer4_Neurons_CPU(Layer4_Neurons_CPU_read_reg_137),
    .Layer3_Neurons_CPU_622_1(Layer3_Neurons_CPU_622_1),
    .Layer3_Neurons_CPU_623_0(Layer3_Neurons_CPU_623_0),
    .Layer3_Neurons_CPU_623_1(Layer3_Neurons_CPU_623_1),
    .Layer3_Neurons_CPU_624_0(Layer3_Neurons_CPU_624_0),
    .Layer3_Neurons_CPU_624_1(Layer3_Neurons_CPU_624_1),
    .grp_generic_tanh_double_s_fu_147_p_din1(grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_din1),
    .grp_generic_tanh_double_s_fu_147_p_dout0(grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_dout0),
    .grp_generic_tanh_double_s_fu_147_p_ce(grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_ce),
    .grp_generic_tanh_double_s_fu_147_p_start(grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_start),
    .grp_generic_tanh_double_s_fu_147_p_ready(grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_ready),
    .grp_generic_tanh_double_s_fu_147_p_done(grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_done),
    .grp_generic_tanh_double_s_fu_147_p_idle(grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_idle),
    .grp_fu_154_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_154_p_din0),
    .grp_fu_154_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_154_p_din1),
    .grp_fu_154_p_opcode(grp_calculateLayer4_1_fu_112_grp_fu_154_p_opcode),
    .grp_fu_154_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_154_p_dout0),
    .grp_fu_154_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_154_p_ce),
    .grp_fu_169_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_169_p_din0),
    .grp_fu_169_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_169_p_din1),
    .grp_fu_169_p_opcode(grp_calculateLayer4_1_fu_112_grp_fu_169_p_opcode),
    .grp_fu_169_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_169_p_dout0),
    .grp_fu_169_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_169_p_ce),
    .grp_fu_173_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_173_p_din0),
    .grp_fu_173_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_173_p_din1),
    .grp_fu_173_p_opcode(grp_calculateLayer4_1_fu_112_grp_fu_173_p_opcode),
    .grp_fu_173_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_173_p_dout0),
    .grp_fu_173_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_173_p_ce),
    .grp_fu_177_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_177_p_din0),
    .grp_fu_177_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_177_p_din1),
    .grp_fu_177_p_opcode(grp_calculateLayer4_1_fu_112_grp_fu_177_p_opcode),
    .grp_fu_177_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_177_p_dout0),
    .grp_fu_177_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_177_p_ce),
    .grp_fu_158_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_158_p_din0),
    .grp_fu_158_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_158_p_din1),
    .grp_fu_158_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_158_p_dout0),
    .grp_fu_158_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_158_p_ce),
    .grp_fu_181_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_181_p_din0),
    .grp_fu_181_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_181_p_din1),
    .grp_fu_181_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_181_p_dout0),
    .grp_fu_181_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_181_p_ce),
    .grp_fu_185_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_185_p_din0),
    .grp_fu_185_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_185_p_din1),
    .grp_fu_185_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_185_p_dout0),
    .grp_fu_185_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_185_p_ce),
    .grp_fu_189_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_189_p_din0),
    .grp_fu_189_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_189_p_din1),
    .grp_fu_189_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_189_p_dout0),
    .grp_fu_189_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_189_p_ce),
    .grp_fu_193_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_193_p_din0),
    .grp_fu_193_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_193_p_din1),
    .grp_fu_193_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_193_p_dout0),
    .grp_fu_193_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_193_p_ce),
    .grp_fu_162_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_162_p_din0),
    .grp_fu_162_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_162_p_dout0),
    .grp_fu_162_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_162_p_ce),
    .grp_fu_165_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_165_p_din0),
    .grp_fu_165_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_165_p_din1),
    .grp_fu_165_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_165_p_dout0),
    .grp_fu_165_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_165_p_ce),
    .grp_fu_197_p_din0(grp_calculateLayer4_1_fu_112_grp_fu_197_p_din0),
    .grp_fu_197_p_din1(grp_calculateLayer4_1_fu_112_grp_fu_197_p_din1),
    .grp_fu_197_p_dout0(grp_calculateLayer4_1_fu_112_grp_fu_197_p_dout0),
    .grp_fu_197_p_ce(grp_calculateLayer4_1_fu_112_grp_fu_197_p_ce)
);

calculateLayer34_generic_tanh_double_s grp_generic_tanh_double_s_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_generic_tanh_double_s_fu_147_ap_start),
    .ap_done(grp_generic_tanh_double_s_fu_147_ap_done),
    .ap_idle(grp_generic_tanh_double_s_fu_147_ap_idle),
    .ap_ready(grp_generic_tanh_double_s_fu_147_ap_ready),
    .ap_ce(grp_generic_tanh_double_s_fu_147_ap_ce),
    .t_in(grp_generic_tanh_double_s_fu_147_t_in),
    .ap_return(grp_generic_tanh_double_s_fu_147_ap_return)
);

calculateLayer34_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U79(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_154_p0),
    .din1(grp_fu_154_p1),
    .ce(grp_fu_154_ce),
    .dout(grp_fu_154_p2)
);

calculateLayer34_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U80(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_158_p0),
    .din1(grp_fu_158_p1),
    .ce(grp_fu_158_ce),
    .dout(grp_fu_158_p2)
);

calculateLayer34_fptrunc_64ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
fptrunc_64ns_32_2_no_dsp_1_U81(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_162_p0),
    .ce(grp_fu_162_ce),
    .dout(grp_fu_162_p1)
);

calculateLayer34_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_4_max_dsp_1_U82(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_165_p0),
    .din1(grp_fu_165_p1),
    .ce(grp_fu_165_ce),
    .dout(grp_fu_165_p2)
);

calculateLayer34_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U83(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_169_p0),
    .din1(grp_fu_169_p1),
    .ce(grp_fu_169_ce),
    .dout(grp_fu_169_p2)
);

calculateLayer34_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U84(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_173_p0),
    .din1(grp_fu_173_p1),
    .ce(grp_fu_173_ce),
    .dout(grp_fu_173_p2)
);

calculateLayer34_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U85(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_177_p0),
    .din1(grp_fu_177_p1),
    .ce(grp_fu_177_ce),
    .dout(grp_fu_177_p2)
);

calculateLayer34_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U86(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_181_p0),
    .din1(grp_fu_181_p1),
    .ce(grp_fu_181_ce),
    .dout(grp_fu_181_p2)
);

calculateLayer34_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U87(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_185_p0),
    .din1(grp_fu_185_p1),
    .ce(grp_fu_185_ce),
    .dout(grp_fu_185_p2)
);

calculateLayer34_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U88(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_189_p0),
    .din1(grp_fu_189_p1),
    .ce(grp_fu_189_ce),
    .dout(grp_fu_189_p2)
);

calculateLayer34_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U89(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_193_p0),
    .din1(grp_fu_193_p1),
    .ce(grp_fu_193_ce),
    .dout(grp_fu_193_p2)
);

calculateLayer34_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_4_max_dsp_1_U90(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_197_p0),
    .din1(grp_fu_197_p1),
    .ce(grp_fu_197_ce),
    .dout(grp_fu_197_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_calculateLayer3_301_302_1_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_calculateLayer3_301_302_1_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_calculateLayer3_301_302_1_fu_86_ap_ready == 1'b1)) begin
            grp_calculateLayer3_301_302_1_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_calculateLayer4_1_fu_112_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_calculateLayer4_1_fu_112_ap_start_reg <= 1'b1;
        end else if ((grp_calculateLayer4_1_fu_112_ap_ready == 1'b1)) begin
            grp_calculateLayer4_1_fu_112_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Layer2_Neurons_CPU_read_reg_142 <= Layer2_Neurons_CPU;
        Layer4_Neurons_CPU_read_reg_137 <= Layer4_Neurons_CPU;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_622_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        Layer3_Neurons_CPU_622_1 <= grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_622_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        Layer3_Neurons_CPU_623_0 <= grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        Layer3_Neurons_CPU_623_1 <= grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_623_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        Layer3_Neurons_CPU_624_0 <= grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        Layer3_Neurons_CPU_624_1 <= grp_calculateLayer3_301_302_1_fu_86_Layer3_Neurons_CPU_624_1;
    end
end

always @ (*) begin
    if (((grp_calculateLayer4_1_fu_112_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_calculateLayer4_1_fu_112_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem0_ARVALID = grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem0_RREADY = grp_calculateLayer3_301_302_1_fu_86_m_axi_gmem0_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_AWVALID = grp_calculateLayer4_1_fu_112_m_axi_gmem1_AWVALID;
    end else begin
        gmem1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_BREADY = grp_calculateLayer4_1_fu_112_m_axi_gmem1_BREADY;
    end else begin
        gmem1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_WVALID = grp_calculateLayer4_1_fu_112_m_axi_gmem1_WVALID;
    end else begin
        gmem1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_154_ce = grp_calculateLayer4_1_fu_112_grp_fu_154_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_154_ce = grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_ce;
    end else begin
        grp_fu_154_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_154_p0 = grp_calculateLayer4_1_fu_112_grp_fu_154_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_154_p0 = grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_154_p1 = grp_calculateLayer4_1_fu_112_grp_fu_154_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_154_p1 = grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_din1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_158_ce = grp_calculateLayer4_1_fu_112_grp_fu_158_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_158_ce = grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_ce;
    end else begin
        grp_fu_158_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_158_p0 = grp_calculateLayer4_1_fu_112_grp_fu_158_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_158_p0 = grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_158_p1 = grp_calculateLayer4_1_fu_112_grp_fu_158_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_158_p1 = grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_din1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_162_ce = grp_calculateLayer4_1_fu_112_grp_fu_162_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_162_ce = grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_ce;
    end else begin
        grp_fu_162_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_162_p0 = grp_calculateLayer4_1_fu_112_grp_fu_162_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_162_p0 = grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_165_ce = grp_calculateLayer4_1_fu_112_grp_fu_165_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_165_ce = grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_ce;
    end else begin
        grp_fu_165_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_165_p0 = grp_calculateLayer4_1_fu_112_grp_fu_165_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_165_p0 = grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_165_p1 = grp_calculateLayer4_1_fu_112_grp_fu_165_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_165_p1 = grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_din1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_169_ce = grp_calculateLayer4_1_fu_112_grp_fu_169_p_ce;
    end else begin
        grp_fu_169_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_173_ce = grp_calculateLayer4_1_fu_112_grp_fu_173_p_ce;
    end else begin
        grp_fu_173_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_177_ce = grp_calculateLayer4_1_fu_112_grp_fu_177_p_ce;
    end else begin
        grp_fu_177_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_181_ce = grp_calculateLayer4_1_fu_112_grp_fu_181_p_ce;
    end else begin
        grp_fu_181_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_185_ce = grp_calculateLayer4_1_fu_112_grp_fu_185_p_ce;
    end else begin
        grp_fu_185_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_189_ce = grp_calculateLayer4_1_fu_112_grp_fu_189_p_ce;
    end else begin
        grp_fu_189_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_193_ce = grp_calculateLayer4_1_fu_112_grp_fu_193_p_ce;
    end else begin
        grp_fu_193_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_197_ce = grp_calculateLayer4_1_fu_112_grp_fu_197_p_ce;
    end else begin
        grp_fu_197_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_generic_tanh_double_s_fu_147_ap_ce = grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_generic_tanh_double_s_fu_147_ap_ce = grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_ce;
    end else begin
        grp_generic_tanh_double_s_fu_147_ap_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_generic_tanh_double_s_fu_147_ap_start = grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_start;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_generic_tanh_double_s_fu_147_ap_start = grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_start;
    end else begin
        grp_generic_tanh_double_s_fu_147_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_generic_tanh_double_s_fu_147_t_in = grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_generic_tanh_double_s_fu_147_t_in = grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_din1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_calculateLayer3_301_302_1_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_calculateLayer4_1_fu_112_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_calculateLayer3_301_302_1_fu_86_ap_start = grp_calculateLayer3_301_302_1_fu_86_ap_start_reg;

assign grp_calculateLayer3_301_302_1_fu_86_grp_fu_154_p_dout0 = grp_fu_154_p2;

assign grp_calculateLayer3_301_302_1_fu_86_grp_fu_158_p_dout0 = grp_fu_158_p2;

assign grp_calculateLayer3_301_302_1_fu_86_grp_fu_162_p_dout0 = grp_fu_162_p1;

assign grp_calculateLayer3_301_302_1_fu_86_grp_fu_165_p_dout0 = grp_fu_165_p2;

assign grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_done = grp_generic_tanh_double_s_fu_147_ap_done;

assign grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_dout0 = grp_generic_tanh_double_s_fu_147_ap_return;

assign grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_idle = grp_generic_tanh_double_s_fu_147_ap_idle;

assign grp_calculateLayer3_301_302_1_fu_86_grp_generic_tanh_double_s_fu_147_p_ready = grp_generic_tanh_double_s_fu_147_ap_ready;

assign grp_calculateLayer4_1_fu_112_ap_start = grp_calculateLayer4_1_fu_112_ap_start_reg;

assign grp_calculateLayer4_1_fu_112_grp_fu_154_p_dout0 = grp_fu_154_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_158_p_dout0 = grp_fu_158_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_162_p_dout0 = grp_fu_162_p1;

assign grp_calculateLayer4_1_fu_112_grp_fu_165_p_dout0 = grp_fu_165_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_169_p_dout0 = grp_fu_169_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_173_p_dout0 = grp_fu_173_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_177_p_dout0 = grp_fu_177_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_181_p_dout0 = grp_fu_181_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_185_p_dout0 = grp_fu_185_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_189_p_dout0 = grp_fu_189_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_193_p_dout0 = grp_fu_193_p2;

assign grp_calculateLayer4_1_fu_112_grp_fu_197_p_dout0 = grp_fu_197_p2;

assign grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_done = grp_generic_tanh_double_s_fu_147_ap_done;

assign grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_dout0 = grp_generic_tanh_double_s_fu_147_ap_return;

assign grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_idle = grp_generic_tanh_double_s_fu_147_ap_idle;

assign grp_calculateLayer4_1_fu_112_grp_generic_tanh_double_s_fu_147_p_ready = grp_generic_tanh_double_s_fu_147_ap_ready;

assign grp_fu_169_p0 = grp_calculateLayer4_1_fu_112_grp_fu_169_p_din0;

assign grp_fu_169_p1 = grp_calculateLayer4_1_fu_112_grp_fu_169_p_din1;

assign grp_fu_173_p0 = grp_calculateLayer4_1_fu_112_grp_fu_173_p_din0;

assign grp_fu_173_p1 = grp_calculateLayer4_1_fu_112_grp_fu_173_p_din1;

assign grp_fu_177_p0 = grp_calculateLayer4_1_fu_112_grp_fu_177_p_din0;

assign grp_fu_177_p1 = grp_calculateLayer4_1_fu_112_grp_fu_177_p_din1;

assign grp_fu_181_p0 = grp_calculateLayer4_1_fu_112_grp_fu_181_p_din0;

assign grp_fu_181_p1 = grp_calculateLayer4_1_fu_112_grp_fu_181_p_din1;

assign grp_fu_185_p0 = grp_calculateLayer4_1_fu_112_grp_fu_185_p_din0;

assign grp_fu_185_p1 = grp_calculateLayer4_1_fu_112_grp_fu_185_p_din1;

assign grp_fu_189_p0 = grp_calculateLayer4_1_fu_112_grp_fu_189_p_din0;

assign grp_fu_189_p1 = grp_calculateLayer4_1_fu_112_grp_fu_189_p_din1;

assign grp_fu_193_p0 = grp_calculateLayer4_1_fu_112_grp_fu_193_p_din0;

assign grp_fu_193_p1 = grp_calculateLayer4_1_fu_112_grp_fu_193_p_din1;

assign grp_fu_197_p0 = grp_calculateLayer4_1_fu_112_grp_fu_197_p_din0;

assign grp_fu_197_p1 = grp_calculateLayer4_1_fu_112_grp_fu_197_p_din1;

endmodule //calculateLayer34
