-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculateLayer34_exp_generic_double_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of calculateLayer34_exp_generic_double_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv71_58B90BFBE8E7BCD5E4 : STD_LOGIC_VECTOR (70 downto 0) := "10110001011100100001011111110111110100011100111101111001101010111100100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_5C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv58_10 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000010000";
    constant ap_const_lv49_0 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_6A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101010";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_7FF0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0111111111110000000000000000000000000000000000000000000000000000";
    constant ap_const_lv13_1C02 : STD_LOGIC_VECTOR (12 downto 0) := "1110000000010";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_69 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101001";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_7FFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "0111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv31_5C55 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000101110001010101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 : STD_LOGIC;
    signal table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0 : STD_LOGIC_VECTOR (57 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 : STD_LOGIC;
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0 : STD_LOGIC_VECTOR (25 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 : STD_LOGIC;
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1 : STD_LOGIC_VECTOR (25 downto 0);
    signal table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 : STD_LOGIC;
    signal table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0 : STD_LOGIC_VECTOR (41 downto 0);
    signal p_Result_9_fu_265_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_1167_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1172_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1180_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln253_fu_341_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln253_reg_1187 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln253_reg_1187_pp0_iter1_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln253_reg_1187_pp0_iter2_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln253_reg_1187_pp0_iter3_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln253_reg_1187_pp0_iter4_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln253_reg_1187_pp0_iter5_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln253_reg_1187_pp0_iter6_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln253_reg_1187_pp0_iter7_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal p_Result_11_reg_1192 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_11_reg_1192_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln657_fu_463_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln657_reg_1202 : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln657_reg_1202_pp0_iter1_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln657_reg_1202_pp0_iter2_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln657_reg_1202_pp0_iter3_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal icmp_ln338_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln338_reg_1207 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln338_reg_1207_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln338_reg_1207_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln338_reg_1207_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln338_reg_1207_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln338_reg_1207_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln338_reg_1207_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln338_reg_1207_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_reg_1215 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_reg_1215_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_reg_1215_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_reg_1215_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_reg_1215_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_reg_1215_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_reg_1215_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1453_reg_1215_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_8_fu_545_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_8_reg_1225 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_8_reg_1225_pp0_iter4_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_8_reg_1225_pp0_iter5_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_8_reg_1225_pp0_iter6_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_8_reg_1225_pp0_iter7_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal m_diff_hi_V_reg_1232 : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_V_reg_1232_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_V_reg_1237 : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_V_reg_1237_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_V_reg_1237_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z3_V_reg_1244 : STD_LOGIC_VECTOR (7 downto 0);
    signal Z3_V_reg_1244_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z4_fu_615_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal Z4_reg_1250 : STD_LOGIC_VECTOR (34 downto 0);
    signal Z4_reg_1250_pp0_iter5_reg : STD_LOGIC_VECTOR (34 downto 0);
    signal Z4_ind_reg_1255 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_10_fu_664_p4 : STD_LOGIC_VECTOR (42 downto 0);
    signal ret_V_10_reg_1275 : STD_LOGIC_VECTOR (42 downto 0);
    signal add_ln657_fu_701_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln657_reg_1280 : STD_LOGIC_VECTOR (35 downto 0);
    signal exp_Z1_V_reg_1290 : STD_LOGIC_VECTOR (57 downto 0);
    signal exp_Z1P_m_1_V_reg_1295 : STD_LOGIC_VECTOR (49 downto 0);
    signal exp_Z1_hi_V_reg_1300 : STD_LOGIC_VECTOR (49 downto 0);
    signal select_ln18_fu_1062_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln18_reg_1305 : STD_LOGIC_VECTOR (63 downto 0);
    signal sel_tmp23_fu_1103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp23_reg_1310 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln488_1_fu_629_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln488_2_fu_633_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln488_fu_637_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln488_3_fu_707_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_V_fu_261_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_22_fu_273_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_23_fu_283_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln209_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln510_fu_317_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_10_fu_327_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal e_frac_V_1_fu_335_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal m_frac_l_V_fu_349_p3 : STD_LOGIC_VECTOR (60 downto 0);
    signal m_exp_fu_321_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln1311_fu_369_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal isNeg_fu_361_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln1311_fu_375_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ush_fu_379_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_prom_i_i360_cast_cast_cast_fu_387_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln256_fu_357_p1 : STD_LOGIC_VECTOR (70 downto 0);
    signal sh_prom_i_i360_cast_cast_cast_cast_fu_391_p1 : STD_LOGIC_VECTOR (70 downto 0);
    signal r_V_fu_395_p2 : STD_LOGIC_VECTOR (70 downto 0);
    signal r_V_1_fu_401_p2 : STD_LOGIC_VECTOR (70 downto 0);
    signal r_V_13_fu_407_p3 : STD_LOGIC_VECTOR (70 downto 0);
    signal m_fix_l_fu_415_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal sh_prom_i_i340_cast_cast_cast_cast_fu_425_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_fix_hi_fu_441_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_3_fu_429_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_V_4_fu_435_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln1322_fu_473_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln_fu_481_p3 : STD_LOGIC_VECTOR (70 downto 0);
    signal rhs_fu_495_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1156_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln805_fu_522_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ret_V_cast_fu_506_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln805_fu_525_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_531_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_s_fu_515_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln804_fu_537_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_8_fu_556_p2 : STD_LOGIC_VECTOR (70 downto 0);
    signal tmp_2_fu_562_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal and_ln_fu_572_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal m_diff_V_fu_580_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal r_fu_641_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln657_fu_651_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln657_1_fu_654_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal ret_V_9_fu_658_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal r_V_10_fu_681_p0 : STD_LOGIC_VECTOR (42 downto 0);
    signal r_V_10_fu_681_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal r_V_10_fu_681_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal trunc_ln657_4_fu_687_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln657_2_fu_697_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln657_3_fu_714_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln1146_fu_711_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_3_fu_723_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal exp_Z2_m_1_V_fu_733_p4 : STD_LOGIC_VECTOR (48 downto 0);
    signal exp_Z2P_m_1_V_fu_717_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal r_V_11_fu_750_p0 : STD_LOGIC_VECTOR (48 downto 0);
    signal r_V_11_fu_750_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal lhs_V_fu_756_p5 : STD_LOGIC_VECTOR (50 downto 0);
    signal r_V_11_fu_750_p2 : STD_LOGIC_VECTOR (92 downto 0);
    signal trunc_ln657_5_fu_771_p4 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln657_4_fu_781_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln657_2_fu_785_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln657_5_fu_791_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln1146_1_fu_767_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal exp_Z1P_m_1_l_V_fu_795_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal r_V_15_fu_832_p0 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_15_fu_832_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal ret_V_11_fu_821_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal r_V_15_fu_832_p2 : STD_LOGIC_VECTOR (99 downto 0);
    signal trunc_ln1146_fu_854_p1 : STD_LOGIC_VECTOR (56 downto 0);
    signal trunc_ln1146_2_fu_870_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal lhs_V_3_fu_838_p3 : STD_LOGIC_VECTOR (106 downto 0);
    signal zext_ln1146_2_fu_846_p1 : STD_LOGIC_VECTOR (106 downto 0);
    signal trunc_ln1146_1_fu_874_p3 : STD_LOGIC_VECTOR (104 downto 0);
    signal zext_ln1146_4_fu_866_p1 : STD_LOGIC_VECTOR (104 downto 0);
    signal trunc_ln1_fu_858_p3 : STD_LOGIC_VECTOR (105 downto 0);
    signal zext_ln1146_3_fu_850_p1 : STD_LOGIC_VECTOR (105 downto 0);
    signal ret_V_6_fu_882_p2 : STD_LOGIC_VECTOR (106 downto 0);
    signal tmp_18_fu_900_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_exp_V_fu_908_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_V_2_fu_913_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_19_fu_920_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln840_fu_930_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_941_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1146_2_fu_894_p2 : STD_LOGIC_VECTOR (105 downto 0);
    signal add_ln1146_1_fu_888_p2 : STD_LOGIC_VECTOR (104 downto 0);
    signal tmp_fu_962_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_s_fu_972_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln167_fu_990_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal out_exp_V_fu_994_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_24_fu_982_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal p_Result_12_fu_1000_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln368_fu_1008_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln18_fu_1016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln338_fu_936_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln338_fu_1031_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln338_fu_1026_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln840_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln840_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln18_fu_1020_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln344_fu_948_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln521_fu_1012_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sel_tmp8_fu_1054_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln338_1_fu_1069_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln840_1_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln338_1_fu_1075_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln840_fu_1085_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln840_2_fu_1091_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp27_fu_1097_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln844_fu_956_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln964_fu_1109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_pinf_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln214_fu_1119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln18_1_fu_1132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_fu_1137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln214_fu_1124_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln18_1_fu_1142_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_1156_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1156_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to8 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal r_V_10_fu_681_p00 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_10_fu_681_p10 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_11_fu_750_p00 : STD_LOGIC_VECTOR (92 downto 0);
    signal r_V_11_fu_750_p10 : STD_LOGIC_VECTOR (92 downto 0);
    signal r_V_15_fu_832_p00 : STD_LOGIC_VECTOR (99 downto 0);
    signal r_V_15_fu_832_p10 : STD_LOGIC_VECTOR (99 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component calculateLayer34_mul_13s_71s_71_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (70 downto 0);
        dout : OUT STD_LOGIC_VECTOR (70 downto 0) );
    end component;


    component calculateLayer34_mul_43ns_36ns_79_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (42 downto 0);
        din1 : IN STD_LOGIC_VECTOR (35 downto 0);
        dout : OUT STD_LOGIC_VECTOR (78 downto 0) );
    end component;


    component calculateLayer34_mul_49ns_44ns_93_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (48 downto 0);
        din1 : IN STD_LOGIC_VECTOR (43 downto 0);
        dout : OUT STD_LOGIC_VECTOR (92 downto 0) );
    end component;


    component calculateLayer34_mul_50ns_50ns_100_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (49 downto 0);
        din1 : IN STD_LOGIC_VECTOR (49 downto 0);
        dout : OUT STD_LOGIC_VECTOR (99 downto 0) );
    end component;


    component calculateLayer34_mac_muladd_16s_16ns_19s_31_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component calculateLayer34_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component calculateLayer34_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component calculateLayer34_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (41 downto 0) );
    end component;



begin
    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U : component calculateLayer34_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb
    generic map (
        DataWidth => 58,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0,
        ce0 => table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0,
        q0 => table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0);

    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U : component calculateLayer34_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud
    generic map (
        DataWidth => 26,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0,
        ce0 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0,
        q0 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0,
        address1 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1,
        ce1 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1,
        q1 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1);

    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U : component calculateLayer34_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe
    generic map (
        DataWidth => 42,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0,
        ce0 => table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0,
        q0 => table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0);

    mul_13s_71s_71_1_1_U1 : component calculateLayer34_mul_13s_71s_71_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 13,
        din1_WIDTH => 71,
        dout_WIDTH => 71)
    port map (
        din0 => ret_V_8_reg_1225,
        din1 => ap_const_lv71_58B90BFBE8E7BCD5E4,
        dout => r_V_8_fu_556_p2);

    mul_43ns_36ns_79_1_1_U2 : component calculateLayer34_mul_43ns_36ns_79_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 43,
        din1_WIDTH => 36,
        dout_WIDTH => 79)
    port map (
        din0 => r_V_10_fu_681_p0,
        din1 => r_V_10_fu_681_p1,
        dout => r_V_10_fu_681_p2);

    mul_49ns_44ns_93_1_1_U3 : component calculateLayer34_mul_49ns_44ns_93_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 49,
        din1_WIDTH => 44,
        dout_WIDTH => 93)
    port map (
        din0 => r_V_11_fu_750_p0,
        din1 => r_V_11_fu_750_p1,
        dout => r_V_11_fu_750_p2);

    mul_50ns_50ns_100_1_1_U4 : component calculateLayer34_mul_50ns_50ns_100_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 50,
        din1_WIDTH => 50,
        dout_WIDTH => 100)
    port map (
        din0 => r_V_15_fu_832_p0,
        din1 => r_V_15_fu_832_p1,
        dout => r_V_15_fu_832_p2);

    mac_muladd_16s_16ns_19s_31_4_1_U5 : component calculateLayer34_mac_muladd_16s_16ns_19s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 19,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => m_fix_hi_fu_441_p4,
        din1 => grp_fu_1156_p1,
        din2 => rhs_fu_495_p3,
        ce => grp_fu_1156_ce,
        dout => grp_fu_1156_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                Z2_V_reg_1237 <= m_diff_V_fu_580_p2(50 downto 43);
                Z2_V_reg_1237_pp0_iter5_reg <= Z2_V_reg_1237;
                Z2_V_reg_1237_pp0_iter6_reg <= Z2_V_reg_1237_pp0_iter5_reg;
                Z3_V_reg_1244 <= m_diff_V_fu_580_p2(42 downto 35);
                Z3_V_reg_1244_pp0_iter5_reg <= Z3_V_reg_1244;
                Z4_ind_reg_1255 <= m_diff_V_fu_580_p2(34 downto 27);
                Z4_reg_1250 <= Z4_fu_615_p1;
                Z4_reg_1250_pp0_iter5_reg <= Z4_reg_1250;
                add_ln657_reg_1280 <= add_ln657_fu_701_p2;
                exp_Z1P_m_1_V_reg_1295 <= exp_Z1P_m_1_l_V_fu_795_p2(51 downto 2);
                exp_Z1_V_reg_1290 <= table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
                exp_Z1_hi_V_reg_1300 <= table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0(57 downto 8);
                icmp_ln1453_reg_1215_pp0_iter2_reg <= icmp_ln1453_reg_1215_pp0_iter1_reg;
                icmp_ln1453_reg_1215_pp0_iter3_reg <= icmp_ln1453_reg_1215_pp0_iter2_reg;
                icmp_ln1453_reg_1215_pp0_iter4_reg <= icmp_ln1453_reg_1215_pp0_iter3_reg;
                icmp_ln1453_reg_1215_pp0_iter5_reg <= icmp_ln1453_reg_1215_pp0_iter4_reg;
                icmp_ln1453_reg_1215_pp0_iter6_reg <= icmp_ln1453_reg_1215_pp0_iter5_reg;
                icmp_ln1453_reg_1215_pp0_iter7_reg <= icmp_ln1453_reg_1215_pp0_iter6_reg;
                icmp_ln338_reg_1207_pp0_iter2_reg <= icmp_ln338_reg_1207_pp0_iter1_reg;
                icmp_ln338_reg_1207_pp0_iter3_reg <= icmp_ln338_reg_1207_pp0_iter2_reg;
                icmp_ln338_reg_1207_pp0_iter4_reg <= icmp_ln338_reg_1207_pp0_iter3_reg;
                icmp_ln338_reg_1207_pp0_iter5_reg <= icmp_ln338_reg_1207_pp0_iter4_reg;
                icmp_ln338_reg_1207_pp0_iter6_reg <= icmp_ln338_reg_1207_pp0_iter5_reg;
                icmp_ln338_reg_1207_pp0_iter7_reg <= icmp_ln338_reg_1207_pp0_iter6_reg;
                m_diff_hi_V_reg_1232 <= m_diff_V_fu_580_p2(58 downto 51);
                m_diff_hi_V_reg_1232_pp0_iter5_reg <= m_diff_hi_V_reg_1232;
                p_Result_9_reg_1167_pp0_iter2_reg <= p_Result_9_reg_1167_pp0_iter1_reg;
                p_Result_9_reg_1167_pp0_iter3_reg <= p_Result_9_reg_1167_pp0_iter2_reg;
                p_Result_9_reg_1167_pp0_iter4_reg <= p_Result_9_reg_1167_pp0_iter3_reg;
                p_Result_9_reg_1167_pp0_iter5_reg <= p_Result_9_reg_1167_pp0_iter4_reg;
                p_Result_9_reg_1167_pp0_iter6_reg <= p_Result_9_reg_1167_pp0_iter5_reg;
                p_Result_9_reg_1167_pp0_iter7_reg <= p_Result_9_reg_1167_pp0_iter6_reg;
                p_Result_9_reg_1167_pp0_iter8_reg <= p_Result_9_reg_1167_pp0_iter7_reg;
                    ret_V_10_reg_1275(25 downto 0) <= ret_V_10_fu_664_p4(25 downto 0);    ret_V_10_reg_1275(42 downto 35) <= ret_V_10_fu_664_p4(42 downto 35);
                ret_V_8_reg_1225 <= ret_V_8_fu_545_p3;
                ret_V_8_reg_1225_pp0_iter4_reg <= ret_V_8_reg_1225;
                ret_V_8_reg_1225_pp0_iter5_reg <= ret_V_8_reg_1225_pp0_iter4_reg;
                ret_V_8_reg_1225_pp0_iter6_reg <= ret_V_8_reg_1225_pp0_iter5_reg;
                ret_V_8_reg_1225_pp0_iter7_reg <= ret_V_8_reg_1225_pp0_iter6_reg;
                sel_tmp23_reg_1310 <= sel_tmp23_fu_1103_p2;
                    select_ln18_reg_1305(62 downto 0) <= select_ln18_fu_1062_p3(62 downto 0);
                select_ln253_reg_1187_pp0_iter2_reg <= select_ln253_reg_1187_pp0_iter1_reg;
                select_ln253_reg_1187_pp0_iter3_reg <= select_ln253_reg_1187_pp0_iter2_reg;
                select_ln253_reg_1187_pp0_iter4_reg <= select_ln253_reg_1187_pp0_iter3_reg;
                select_ln253_reg_1187_pp0_iter5_reg <= select_ln253_reg_1187_pp0_iter4_reg;
                select_ln253_reg_1187_pp0_iter6_reg <= select_ln253_reg_1187_pp0_iter5_reg;
                select_ln253_reg_1187_pp0_iter7_reg <= select_ln253_reg_1187_pp0_iter6_reg;
                trunc_ln657_reg_1202_pp0_iter2_reg <= trunc_ln657_reg_1202_pp0_iter1_reg;
                trunc_ln657_reg_1202_pp0_iter3_reg <= trunc_ln657_reg_1202_pp0_iter2_reg;
                x_is_NaN_reg_1172_pp0_iter2_reg <= x_is_NaN_reg_1172_pp0_iter1_reg;
                x_is_NaN_reg_1172_pp0_iter3_reg <= x_is_NaN_reg_1172_pp0_iter2_reg;
                x_is_NaN_reg_1172_pp0_iter4_reg <= x_is_NaN_reg_1172_pp0_iter3_reg;
                x_is_NaN_reg_1172_pp0_iter5_reg <= x_is_NaN_reg_1172_pp0_iter4_reg;
                x_is_NaN_reg_1172_pp0_iter6_reg <= x_is_NaN_reg_1172_pp0_iter5_reg;
                x_is_NaN_reg_1172_pp0_iter7_reg <= x_is_NaN_reg_1172_pp0_iter6_reg;
                x_is_NaN_reg_1172_pp0_iter8_reg <= x_is_NaN_reg_1172_pp0_iter7_reg;
                x_is_inf_reg_1180_pp0_iter2_reg <= x_is_inf_reg_1180_pp0_iter1_reg;
                x_is_inf_reg_1180_pp0_iter3_reg <= x_is_inf_reg_1180_pp0_iter2_reg;
                x_is_inf_reg_1180_pp0_iter4_reg <= x_is_inf_reg_1180_pp0_iter3_reg;
                x_is_inf_reg_1180_pp0_iter5_reg <= x_is_inf_reg_1180_pp0_iter4_reg;
                x_is_inf_reg_1180_pp0_iter6_reg <= x_is_inf_reg_1180_pp0_iter5_reg;
                x_is_inf_reg_1180_pp0_iter7_reg <= x_is_inf_reg_1180_pp0_iter6_reg;
                x_is_inf_reg_1180_pp0_iter8_reg <= x_is_inf_reg_1180_pp0_iter7_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1453_reg_1215 <= icmp_ln1453_fu_489_p2;
                icmp_ln1453_reg_1215_pp0_iter1_reg <= icmp_ln1453_reg_1215;
                icmp_ln338_reg_1207 <= icmp_ln338_fu_467_p2;
                icmp_ln338_reg_1207_pp0_iter1_reg <= icmp_ln338_reg_1207;
                p_Result_11_reg_1192 <= r_V_13_fu_407_p3(70 downto 70);
                p_Result_11_reg_1192_pp0_iter1_reg <= p_Result_11_reg_1192;
                p_Result_9_reg_1167 <= data_V_fu_261_p1(63 downto 63);
                p_Result_9_reg_1167_pp0_iter1_reg <= p_Result_9_reg_1167;
                select_ln253_reg_1187 <= select_ln253_fu_341_p3;
                select_ln253_reg_1187_pp0_iter1_reg <= select_ln253_reg_1187;
                trunc_ln657_reg_1202 <= trunc_ln657_fu_463_p1;
                trunc_ln657_reg_1202_pp0_iter1_reg <= trunc_ln657_reg_1202;
                x_is_NaN_reg_1172 <= x_is_NaN_fu_299_p2;
                x_is_NaN_reg_1172_pp0_iter1_reg <= x_is_NaN_reg_1172;
                x_is_inf_reg_1180 <= x_is_inf_fu_311_p2;
                x_is_inf_reg_1180_pp0_iter1_reg <= x_is_inf_reg_1180;
            end if;
        end if;
    end process;
    ret_V_10_reg_1275(34 downto 26) <= "000000000";
    select_ln18_reg_1305(63) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Z4_fu_615_p1 <= m_diff_V_fu_580_p2(35 - 1 downto 0);
    add_ln1146_1_fu_888_p2 <= std_logic_vector(unsigned(trunc_ln1146_1_fu_874_p3) + unsigned(zext_ln1146_4_fu_866_p1));
    add_ln1146_2_fu_894_p2 <= std_logic_vector(unsigned(trunc_ln1_fu_858_p3) + unsigned(zext_ln1146_3_fu_850_p1));
    add_ln657_2_fu_785_p2 <= std_logic_vector(unsigned(exp_Z2P_m_1_V_fu_717_p2) + unsigned(zext_ln657_4_fu_781_p1));
    add_ln657_fu_701_p2 <= std_logic_vector(unsigned(ret_V_9_fu_658_p2) + unsigned(zext_ln657_2_fu_697_p1));
    and_ln18_fu_1137_p2 <= (xor_ln18_1_fu_1132_p2 and x_is_inf_reg_1180_pp0_iter8_reg);
    and_ln338_1_fu_1075_p2 <= (xor_ln338_1_fu_1069_p2 and icmp_ln338_reg_1207_pp0_iter7_reg);
    and_ln338_fu_1026_p2 <= (or_ln338_fu_936_p2 and icmp_ln338_reg_1207_pp0_iter7_reg);
    and_ln840_fu_1036_p2 <= (xor_ln338_fu_1031_p2 and icmp_ln840_fu_930_p2);
    and_ln_fu_572_p3 <= (tmp_2_fu_562_p4 & ap_const_lv1_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to8_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to8 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to8)
    begin
        if (((ap_idle_pp0_0to8 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        ap_const_lv64_0 when (sel_tmp23_reg_1310(0) = '1') else 
        select_ln18_1_fu_1142_p3;
    bitcast_ln521_fu_1012_p1 <= zext_ln368_fu_1008_p1;
    data_V_fu_261_p1 <= x;
    e_frac_V_1_fu_335_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(p_Result_10_fu_327_p3));
    exp_Z1P_m_1_l_V_fu_795_p2 <= std_logic_vector(unsigned(zext_ln657_5_fu_791_p1) + unsigned(zext_ln1146_1_fu_767_p1));
    exp_Z2P_m_1_V_fu_717_p2 <= std_logic_vector(unsigned(zext_ln657_3_fu_714_p1) + unsigned(zext_ln1146_fu_711_p1));
    exp_Z2_m_1_V_fu_733_p4 <= ((Z2_V_reg_1237_pp0_iter6_reg & ap_const_lv1_0) & tmp_3_fu_723_p4);

    grp_fu_1156_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_1156_ce <= ap_const_logic_1;
        else 
            grp_fu_1156_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1156_p1 <= ap_const_lv31_5C55(16 - 1 downto 0);
    icmp_ln1453_fu_489_p2 <= "0" when (shl_ln_fu_481_p3 = sext_ln256_fu_357_p1) else "1";
    icmp_ln18_fu_293_p2 <= "0" when (tmp_23_fu_283_p1 = ap_const_lv52_0) else "1";
    icmp_ln209_fu_287_p2 <= "1" when (tmp_22_fu_273_p4 = ap_const_lv11_7FF) else "0";
    icmp_ln338_fu_467_p2 <= "1" when (signed(m_exp_fu_321_p2) > signed(ap_const_lv12_0)) else "0";
    icmp_ln805_fu_525_p2 <= "1" when (trunc_ln805_fu_522_p1 = ap_const_lv18_0) else "0";
    icmp_ln824_fu_305_p2 <= "1" when (tmp_23_fu_283_p1 = ap_const_lv52_0) else "0";
    icmp_ln840_fu_930_p2 <= "1" when (signed(tmp_19_fu_920_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln844_fu_956_p2 <= "1" when (signed(r_exp_V_2_fu_913_p3) < signed(ap_const_lv13_1C02)) else "0";
    isNeg_fu_361_p3 <= m_exp_fu_321_p2(11 downto 11);
    lhs_V_3_fu_838_p3 <= (ret_V_11_fu_821_p2 & ap_const_lv49_0);
    lhs_V_fu_756_p5 <= (((Z2_V_reg_1237_pp0_iter6_reg & ap_const_lv1_0) & tmp_3_fu_723_p4) & ap_const_lv2_0);
    m_diff_V_fu_580_p2 <= std_logic_vector(unsigned(trunc_ln657_reg_1202_pp0_iter3_reg) - unsigned(and_ln_fu_572_p3));
    m_exp_fu_321_p2 <= std_logic_vector(unsigned(zext_ln510_fu_317_p1) + unsigned(ap_const_lv12_C01));
    m_fix_hi_fu_441_p4 <= r_V_13_fu_407_p3(70 downto 55);
    m_fix_l_fu_415_p4 <= r_V_13_fu_407_p3(70 downto 7);
    m_frac_l_V_fu_349_p3 <= (select_ln253_fu_341_p3 & ap_const_lv7_0);
    or_ln18_fu_1016_p2 <= (x_is_inf_reg_1180_pp0_iter7_reg or x_is_NaN_reg_1172_pp0_iter7_reg);
    or_ln214_fu_1119_p2 <= (x_is_pinf_fu_1114_p2 or x_is_NaN_reg_1172_pp0_iter8_reg);
    or_ln338_fu_936_p2 <= (icmp_ln840_fu_930_p2 or icmp_ln1453_reg_1215_pp0_iter7_reg);
    or_ln840_1_fu_1080_p2 <= (icmp_ln840_fu_930_p2 or icmp_ln338_reg_1207_pp0_iter7_reg);
    or_ln840_2_fu_1091_p2 <= (xor_ln840_fu_1085_p2 or and_ln338_1_fu_1075_p2);
    or_ln840_fu_1042_p2 <= (and_ln840_fu_1036_p2 or and_ln338_fu_1026_p2);
    out_exp_V_fu_994_p2 <= std_logic_vector(unsigned(trunc_ln167_fu_990_p1) + unsigned(ap_const_lv11_3FF));
    p_Result_10_fu_327_p3 <= (ap_const_lv2_1 & tmp_23_fu_283_p1);
    p_Result_12_fu_1000_p3 <= (out_exp_V_fu_994_p2 & tmp_24_fu_982_p3);
    p_Result_9_fu_265_p3 <= data_V_fu_261_p1(63 downto 63);
    p_Result_s_fu_515_p3 <= grp_fu_1156_p3(30 downto 30);
    r_V_10_fu_681_p0 <= r_V_10_fu_681_p00(43 - 1 downto 0);
    r_V_10_fu_681_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_10_fu_664_p4),79));
    r_V_10_fu_681_p1 <= r_V_10_fu_681_p10(36 - 1 downto 0);
    r_V_10_fu_681_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_9_fu_658_p2),79));
    r_V_11_fu_750_p0 <= r_V_11_fu_750_p00(49 - 1 downto 0);
    r_V_11_fu_750_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z2_m_1_V_fu_733_p4),93));
    r_V_11_fu_750_p1 <= r_V_11_fu_750_p10(44 - 1 downto 0);
    r_V_11_fu_750_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z2P_m_1_V_fu_717_p2),93));
    r_V_13_fu_407_p3 <= 
        r_V_fu_395_p2 when (isNeg_fu_361_p3(0) = '1') else 
        r_V_1_fu_401_p2;
    r_V_15_fu_832_p0 <= r_V_15_fu_832_p00(50 - 1 downto 0);
    r_V_15_fu_832_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z1P_m_1_V_reg_1295),100));
    r_V_15_fu_832_p1 <= r_V_15_fu_832_p10(50 - 1 downto 0);
    r_V_15_fu_832_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z1_hi_V_reg_1300),100));
    r_V_1_fu_401_p2 <= std_logic_vector(shift_left(unsigned(sext_ln256_fu_357_p1),to_integer(unsigned('0' & sh_prom_i_i360_cast_cast_cast_cast_fu_391_p1(31-1 downto 0)))));
    r_V_3_fu_429_p2 <= std_logic_vector(shift_left(unsigned(m_fix_l_fu_415_p4),to_integer(unsigned('0' & sh_prom_i_i340_cast_cast_cast_cast_fu_425_p1(31-1 downto 0)))));
    r_V_4_fu_435_p2 <= std_logic_vector(shift_right(signed(m_fix_l_fu_415_p4),to_integer(unsigned('0' & sh_prom_i_i340_cast_cast_cast_cast_fu_425_p1(31-1 downto 0)))));
    r_V_fu_395_p2 <= std_logic_vector(shift_right(signed(sext_ln256_fu_357_p1),to_integer(unsigned('0' & sh_prom_i_i360_cast_cast_cast_cast_fu_391_p1(31-1 downto 0)))));
    r_exp_V_2_fu_913_p3 <= 
        ret_V_8_reg_1225_pp0_iter7_reg when (tmp_18_fu_900_p3(0) = '1') else 
        r_exp_V_fu_908_p2;
    r_exp_V_fu_908_p2 <= std_logic_vector(signed(ret_V_8_reg_1225_pp0_iter7_reg) + signed(ap_const_lv13_1FFF));
    r_fu_641_p4 <= table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1(25 downto 16);
    ret_V_10_fu_664_p4 <= ((Z3_V_reg_1244_pp0_iter5_reg & ap_const_lv9_0) & table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0);
    ret_V_11_fu_821_p2 <= std_logic_vector(unsigned(exp_Z1_V_reg_1290) + unsigned(ap_const_lv58_10));
    ret_V_6_fu_882_p2 <= std_logic_vector(unsigned(lhs_V_3_fu_838_p3) + unsigned(zext_ln1146_2_fu_846_p1));
    ret_V_8_fu_545_p3 <= 
        select_ln804_fu_537_p3 when (p_Result_s_fu_515_p3(0) = '1') else 
        ret_V_cast_fu_506_p4;
    ret_V_9_fu_658_p2 <= std_logic_vector(unsigned(zext_ln657_fu_651_p1) + unsigned(zext_ln657_1_fu_654_p1));
    ret_V_cast_fu_506_p4 <= grp_fu_1156_p3(30 downto 18);
    ret_V_fu_531_p2 <= std_logic_vector(unsigned(ret_V_cast_fu_506_p4) + unsigned(ap_const_lv13_1));
    rhs_fu_495_p3 <= (p_Result_11_reg_1192_pp0_iter1_reg & ap_const_lv18_20000);
    sel_tmp23_fu_1103_p2 <= (tmp27_fu_1097_p2 and icmp_ln844_fu_956_p2);
    sel_tmp7_fu_1048_p2 <= (xor_ln18_fu_1020_p2 and or_ln840_fu_1042_p2);
    sel_tmp8_fu_1054_p3 <= 
        select_ln344_fu_948_p3 when (sel_tmp7_fu_1048_p2(0) = '1') else 
        bitcast_ln521_fu_1012_p1;
    select_ln1322_fu_473_p3 <= 
        r_V_3_fu_429_p2 when (isNeg_fu_361_p3(0) = '1') else 
        r_V_4_fu_435_p2;
    select_ln18_1_fu_1142_p3 <= 
        select_ln214_fu_1124_p3 when (and_ln18_fu_1137_p2(0) = '1') else 
        select_ln18_reg_1305;
    select_ln18_fu_1062_p3 <= 
        ap_const_lv64_7FFFFFFFFFFFFFFF when (x_is_NaN_reg_1172_pp0_iter7_reg(0) = '1') else 
        sel_tmp8_fu_1054_p3;
    select_ln214_fu_1124_p3 <= 
        ap_const_lv64_7FF0000000000000 when (or_ln214_fu_1119_p2(0) = '1') else 
        ap_const_lv64_0;
    select_ln253_fu_341_p3 <= 
        e_frac_V_1_fu_335_p2 when (p_Result_9_fu_265_p3(0) = '1') else 
        p_Result_10_fu_327_p3;
    select_ln344_fu_948_p3 <= 
        ap_const_lv64_0 when (tmp_20_fu_941_p3(0) = '1') else 
        ap_const_lv64_7FF0000000000000;
    select_ln804_fu_537_p3 <= 
        ret_V_cast_fu_506_p4 when (icmp_ln805_fu_525_p2(0) = '1') else 
        ret_V_fu_531_p2;
        sext_ln1311_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1311_fu_369_p2),12));

        sext_ln256_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m_frac_l_V_fu_349_p3),71));

    sh_prom_i_i340_cast_cast_cast_cast_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_prom_i_i360_cast_cast_cast_fu_387_p1),64));
    sh_prom_i_i360_cast_cast_cast_cast_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_prom_i_i360_cast_cast_cast_fu_387_p1),71));
        sh_prom_i_i360_cast_cast_cast_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_fu_379_p3),32));

    shl_ln_fu_481_p3 <= (select_ln1322_fu_473_p3 & ap_const_lv7_0);
    sub_ln1311_fu_369_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(tmp_22_fu_273_p4));
    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 <= zext_ln488_fu_637_p1(8 - 1 downto 0);

    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_1;
        else 
            table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 <= zext_ln488_3_fu_707_p1(8 - 1 downto 0);

    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_1;
        else 
            table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 <= zext_ln488_2_fu_633_p1(8 - 1 downto 0);
    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1 <= zext_ln488_1_fu_629_p1(8 - 1 downto 0);

    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_1;
        else 
            table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 <= ap_const_logic_1;
        else 
            table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp27_fu_1097_p2 <= (xor_ln18_fu_1020_p2 and or_ln840_2_fu_1091_p2);
    tmp_18_fu_900_p3 <= ret_V_6_fu_882_p2(106 downto 106);
    tmp_19_fu_920_p4 <= r_exp_V_2_fu_913_p3(12 downto 10);
    tmp_20_fu_941_p3 <= select_ln253_reg_1187_pp0_iter7_reg(53 downto 53);
    tmp_22_fu_273_p4 <= data_V_fu_261_p1(62 downto 52);
    tmp_23_fu_283_p1 <= data_V_fu_261_p1(52 - 1 downto 0);
    tmp_24_fu_982_p3 <= 
        tmp_fu_962_p4 when (tmp_18_fu_900_p3(0) = '1') else 
        tmp_s_fu_972_p4;
    tmp_2_fu_562_p4 <= r_V_8_fu_556_p2(70 downto 13);
    tmp_3_fu_723_p4 <= table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0(41 downto 2);
    tmp_fu_962_p4 <= add_ln1146_2_fu_894_p2(105 downto 54);
    tmp_s_fu_972_p4 <= add_ln1146_1_fu_888_p2(104 downto 53);
    trunc_ln1146_1_fu_874_p3 <= (trunc_ln1146_2_fu_870_p1 & ap_const_lv49_0);
    trunc_ln1146_2_fu_870_p1 <= ret_V_11_fu_821_p2(56 - 1 downto 0);
    trunc_ln1146_fu_854_p1 <= ret_V_11_fu_821_p2(57 - 1 downto 0);
    trunc_ln167_fu_990_p1 <= r_exp_V_2_fu_913_p3(11 - 1 downto 0);
    trunc_ln1_fu_858_p3 <= (trunc_ln1146_fu_854_p1 & ap_const_lv49_0);
    trunc_ln657_4_fu_687_p4 <= r_V_10_fu_681_p2(78 downto 59);
    trunc_ln657_5_fu_771_p4 <= r_V_11_fu_750_p2(92 downto 57);
    trunc_ln657_fu_463_p1 <= r_V_13_fu_407_p3(59 - 1 downto 0);
    trunc_ln805_fu_522_p1 <= grp_fu_1156_p3(18 - 1 downto 0);
    ush_fu_379_p3 <= 
        sext_ln1311_fu_375_p1 when (isNeg_fu_361_p3(0) = '1') else 
        m_exp_fu_321_p2;
    x_is_NaN_fu_299_p2 <= (icmp_ln209_fu_287_p2 and icmp_ln18_fu_293_p2);
    x_is_inf_fu_311_p2 <= (icmp_ln824_fu_305_p2 and icmp_ln209_fu_287_p2);
    x_is_pinf_fu_1114_p2 <= (xor_ln964_fu_1109_p2 and x_is_inf_reg_1180_pp0_iter8_reg);
    xor_ln18_1_fu_1132_p2 <= (x_is_NaN_reg_1172_pp0_iter8_reg xor ap_const_lv1_1);
    xor_ln18_fu_1020_p2 <= (or_ln18_fu_1016_p2 xor ap_const_lv1_1);
    xor_ln338_1_fu_1069_p2 <= (or_ln338_fu_936_p2 xor ap_const_lv1_1);
    xor_ln338_fu_1031_p2 <= (icmp_ln338_reg_1207_pp0_iter7_reg xor ap_const_lv1_1);
    xor_ln840_fu_1085_p2 <= (or_ln840_1_fu_1080_p2 xor ap_const_lv1_1);
    xor_ln964_fu_1109_p2 <= (p_Result_9_reg_1167_pp0_iter8_reg xor ap_const_lv1_1);
    zext_ln1146_1_fu_767_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lhs_V_fu_756_p5),52));
    zext_ln1146_2_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_15_fu_832_p2),107));
    zext_ln1146_3_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_15_fu_832_p2),106));
    zext_ln1146_4_fu_866_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_15_fu_832_p2),105));
    zext_ln1146_fu_711_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_10_reg_1275),44));
    zext_ln368_fu_1008_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_12_fu_1000_p3),64));
    zext_ln488_1_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z4_ind_reg_1255),64));
    zext_ln488_2_fu_633_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z3_V_reg_1244),64));
    zext_ln488_3_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z2_V_reg_1237_pp0_iter5_reg),64));
    zext_ln488_fu_637_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_diff_hi_V_reg_1232_pp0_iter5_reg),64));
    zext_ln510_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_fu_273_p4),12));
    zext_ln657_1_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_641_p4),36));
    zext_ln657_2_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln657_4_fu_687_p4),36));
    zext_ln657_3_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln657_reg_1280),44));
    zext_ln657_4_fu_781_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln657_5_fu_771_p4),44));
    zext_ln657_5_fu_791_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln657_2_fu_785_p2),52));
    zext_ln657_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z4_reg_1250_pp0_iter5_reg),36));
end behav;
